OCPI_DIR=../../../ocpi
# Which component libraries should be referenced to build this app?
OcpiLibraries=../../../components
XmlIncludeDirs += ../../platform
# For which containers should the runtime xml be generated?
# These (for now) just xml files containing HdlContainer elements.
Containers=psdEcv5
Target=xc5vsx95t-2-ff1136
include $(OCPI_DIR)/include/hdl/hdl-app.mk
