% Generated on Fri Sep 28 16:14:07 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {7}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: data\_src}\\
        \hline
        \rowcolor{blue}
            Configuration & ZLM\_WHEN\_NUM\_SAMPLES\_REACHED\_p & LFSR\_POLYNOMIAL\_p & DATA\_BIT\_WIDTH\_p & ocpi\_endian & ocpi\_debug & LFSR\_SEED\_p \\
            \hline
            0             & true                                & 111000001000        & 12                  & little       & false       & 111111111111 \\
            \hline
            1             & false                               & 111000001000        & 12                  & little       & false       & 111111111111 \\
            \hline
        \end{longtable}
\end{tiny}
