% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {6}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: data\_src}\\
        \hline
        \rowcolor{blue}
            Configuration & DATA\_BIT\_WIDTH\_p & ODATA\_WIDTH\_p & LFSR\_SEED\_p & ZLM\_WHEN\_NUM\_SAMPLES\_REACHED\_p & LFSR\_POLYNOMIAL\_p \\
            \hline
            0             & 12                  & 32              & 111111111111  & true                                & 111000001000 \\
            \hline
            1             & 12                  & 32              & 111111111111  & false                               & 111000001000 \\
            \hline
        \end{longtable}
\end{tiny}
