%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "data_src"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+LFSR_POLYNOMIAL_p=1,1,1,0,0,0,0,0,1,0,0,0+
	\item \verb+DATA_BIT_WIDTH_p=12+
	\item \verb+LFSR_SEED_p=1,1,1,1,1,1,1,1,1,1,1,1+
	\item \verb+ZLM_WHEN_NUM_SAMPLES_REACHED_p=true+
	\item \verb+ocpi_endian=little+
	\item \verb+ocpi_debug=false+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 270       & 404  & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 257       & 332  & 304.807    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 269       & 348  & 258.598    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 255       & 332  & 369.753    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
%\textbf{Worker Build Configuration ``1'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+LFSR_POLYNOMIAL_p=1,1,1,0,0,0,0,0,1,0,0,0+
%	\item \verb+DATA_BIT_WIDTH_p=12+
%	\item \verb+LFSR_SEED_p=1,1,1,1,1,1,1,1,1,1,1,1+
%	\item \verb+ZLM_WHEN_NUM_SAMPLES_REACHED_p=false+
%	\item \verb+ocpi_endian=little+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``1''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 269       & 401  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 256       & 408  & 331.614    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 268       & 328  & 260.485    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 254       & 408  & 416.476    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
