% Generated on Fri Oct  5 08:45:55 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: data\_src}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 306             & 400        & N/A              & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 292             & 432        & 189.387          & N/A \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 307             & 475        & N/A              & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 302             & 374        & N/A              & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 288             & 421        & 296.212          & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 303             & 460        & N/A              & N/A \\
            \hline
        \end{longtable}
\end{tiny}
