% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "data\_src"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 342             & 614        & N/A              & N/A \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 339             & 482        & N/A              & N/A \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 322             & 610        & 211.211          & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 322             & 610        & 168.108          & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 319             & 543        & N/A              & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 335             & 452        & N/A              & N/A \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 318             & 607        & 293.462          & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 318             & 607        & 231.801          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
