Workers=zcprod zccons zcloop
WorkerSourceFiles=
SourceFiles=zcworkers.c
# name the output shared library.  default is first worker
BinaryName=zcworkers
OCPI_DIR=../../ocpi
# Set this if some of the xml files are elsewhere, like a spec file that is being
# shared with other implementers
IncludeDirs=../../core/local/util/timeEmit/include
include $(OCPI_DIR)/include/rcc/rcc-worker.mk
