Core=pcie_4243_trn_v6_gtx_x4_250
Top=v6_pcie_v1_7
ExcludeTargets=
OnlyTargets=virtex6 isim
SourceFiles=\
 pcie_upconfig_fix_3451_v6.v\
 pcie_reset_delay_v6.v\
 pcie_brams_v6.v\
 pcie_clocking_v6.v\
 pcie_gtx_v6.v\
 pcie_pipe_v6.v\
 pcie_pipe_lane_v6.v\
 pcie_pipe_misc_v6.v\
 pcie_2_0_v6.v\
 pcie_bram_v6.v\
 pcie_bram_top_v6.v\
 gtx_rx_valid_filter_v6.v\
 gtx_drp_chanalign_fix_3752_v6.v\
 gtx_tx_sync_rate_v6.v\
 v6_pcie_v1_7.v\
 gtx_wrapper_v6.v\
# end of files
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk
