# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

Core=pcie_4243_trn_v6_gtx_x4_250
Top=v6_pcie_v1_7
ExcludeTargets=
OnlyTargets=virtex6 isim xsim
SourceFiles=\
 pcie_upconfig_fix_3451_v6.v\
 pcie_reset_delay_v6.v\
 pcie_brams_v6.v\
 pcie_clocking_v6.v\
 pcie_gtx_v6.v\
 pcie_pipe_v6.v\
 pcie_pipe_lane_v6.v\
 pcie_pipe_misc_v6.v\
 pcie_2_0_v6.v\
 pcie_bram_v6.v\
 pcie_bram_top_v6.v\
 gtx_rx_valid_filter_v6.v\
 gtx_drp_chanalign_fix_3752_v6.v\
 gtx_tx_sync_rate_v6.v\
 v6_pcie_v1_7.v\
 gtx_wrapper_v6.v\
# end of files
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk
