#!/bin/csh -f
# Update a local file $1 with remote file $2 from OCPI_HDL_IMPORTS_DIR
if ($#argv == 0) then
  echo This command updates a local worker verilog file from a BSV generated one.
  echo "Usage is:  $0:t <impl-to-update> <source-file-to-use> [<srcdir> = $OCPI_HDL_IMPORTS_DIR/rtl]"
  exit 1
endif
if ($#argv == 3) then
set src=$3
else
set src=$OCPI_HDL_IMPORTS_DIR/rtl
endif
set d=$1.hdl
cp $d/$1.v $d/$1.v.`date +%F-%T`
cp $src/$2.v $d/$1.v
set x = $1:t
set x = $x:r
ed -s $d/$1.v<<EOF
H
/module /i
\`ifdef ORIGINAL
.
/\/\/ signals for module outputs/i
\`else
\`define NOT_EMPTY_$1
\`include "$1_defs.vh"
\`endif
.
.ka
/assign/
-kb
.=
'a=
'b=
'a,'bs/\\([a-zA-Z_0-9]*SThreadBusy\\),/[0:0]\\1; wire /g
.=
+
.=
'b+1,\$s/\\([a-zA-Z_0-9]*SThreadBusy\\)\\([^a-zA-Z_0-9]\\)/\\1[0]\\2/g
.=
w
EOF
echo Imported $src/$2.v for $1
