#!/bin/bash
# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

# "sudo -E" does not preserve $PATH (for security reasons)
# So use this script instead to start commands in cdk scripts or bin dirs as root
if test "0`/usr/bin/id -u 2>&1`" -eq 0; then
  exec $*
fi
cmd=$1
shift
exec sudo -E LD_LIBRARY_PATH=$LD_LIBRARY_PATH PATH=$PATH `which $cmd` $*
