% Generated on Fri Oct  5 08:47:24 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: empty}\\
        \hline
        \rowcolor{blue}
            Container                                                       & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base                                                            & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            base                                                            & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 2091            & 1994       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base                                                            & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1728            & 1781       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base                                                            & e3xx          & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 2045            & 2000       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base                                                            & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17624           & 10670      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 137772 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605       & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1728            & 1781       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_matchstiq\_z1                         & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 2091            & 1994       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_hpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_hsmc\_a\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17624           & 10670      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 137772 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_hsmc\_b\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17624           & 10670      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 137772 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_lpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_lpc\_zed                      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1728            & 1781       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_fmcomms\_2\_3\_hpc\_LVDS\_ml605       & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605       & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1728            & 1781       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_matchstiq\_z1                         & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 2091            & 1994       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_hpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_hsmc\_a\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17624           & 10670      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 137772 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_hsmc\_b\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17624           & 10670      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 137772 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_lpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_lpc\_zed                      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1728            & 1781       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605       & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1728            & 1781       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_matchstiq\_z1                         & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 2091            & 1994       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_hpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_hsmc\_a\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17624           & 10670      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 137772 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_hsmc\_b\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17624           & 10670      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 137772 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_lpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4597            & 4771       & 126.743          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_lpc\_zed                      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1728            & 1781       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_2rx\_2tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1728            & 1781       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 2 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_hsmc\_alst4\_debug\_header\_breakout\_card\_hsmc\_alst4\_a & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17624           & 10670      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 137772 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_hsmc\_alst4\_debug\_header\_breakout\_card\_hsmc\_alst4\_b & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17624           & 10670      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 137772 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
