% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "empty"}\\
        \hline
        \rowcolor{blue}
            Container                                                       & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base                                                            & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17601           & 10671      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 137772 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            base                                                            & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 2049            & 1957       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            base                                                            & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1686            & 1761       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            base                                                            & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1606            & 2110       & 101.153          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            base                                                            & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605       & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1686            & 1761       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1606            & 2110       & 101.153          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_matchstiq\_z1                         & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 2049            & 1957       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_hpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_hsmc\_a\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17601           & 10671      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 137772 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_hsmc\_b\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17601           & 10671      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 137772 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_lpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_lpc\_zed                      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1686            & 1761       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_zipper\_lpc\_zed                      & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1606            & 2110       & 101.153          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_fmcomms\_2\_3\_hpc\_LVDS\_ml605       & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605       & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1686            & 1761       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1606            & 2110       & 101.153          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_matchstiq\_z1                         & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 2049            & 1957       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_hpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_hsmc\_a\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17601           & 10671      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 137772 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_hsmc\_b\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17601           & 10671      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 137772 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_lpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_lpc\_zed                      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1686            & 1761       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_zipper\_lpc\_zed                      & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1606            & 2110       & 101.153          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605       & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1686            & 1761       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1606            & 2110       & 101.153          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_matchstiq\_z1                         & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 2049            & 1957       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_hpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_hsmc\_a\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17601           & 10671      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 137772 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_hsmc\_b\_alst4                & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17601           & 10671      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 137772 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_lpc\_ml605                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4567            & 4691       & 130.005          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_lpc\_zed                      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1686            & 1761       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_zipper\_lpc\_zed                      & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1606            & 2110       & 101.153          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_2rx\_2tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1686            & 1761       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2\end{tabular} \\
            \hline
            cnt\_2rx\_2tx\_bypassasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed         & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1606            & 2110       & 101.153          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_hsmc\_alst4\_debug\_header\_breakout\_card\_hsmc\_alst4\_a & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17601           & 10671      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 137772 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_hsmc\_alst4\_debug\_header\_breakout\_card\_hsmc\_alst4\_b & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 17601           & 10671      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 137772 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
