# Some sources for these files
# 1. pcie_hip_s4gx_gen2_x4_128_rs_hip.v comes from the result of the PCIE core 
#    megawizard, but just in the dma example subdirectory, and not used in the core
#        pcie_hip_s4gx_gen2_x4_128_examples/chaining_dma
# 2. altpcie_reconfig_4sgx.v comes from the PCIE megawizard library, but is not 
#    used in that core
#        pci_express_compiler-library/altpcie_reconfig_4sgx.v
# 3. pll1.v comes from a separate megawizard, and just instantiates altpll_component
#    the pll1.qip and pll1.ppf are present until we make this a proper core
OnlyTargets=stratix4
HdlNoLibraries=yes
include $(OCPI_CDK_DIR)/include/hdl/hdl-lib.mk




