% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "iq\_imbalance\_fixer"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1063            & 1256       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 14\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 818             & 1229       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 7\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 830             & 1713       & 161.734          & \begin{tabular}{@{}l@{}}DSP48E1: 7\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 830             & 1700       & 163.988          & \begin{tabular}{@{}l@{}}DSP48E1: 7\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
