%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "iq_imbalance_fixer"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs  & Fmax (MHz) & Memory/Special Functions                         \\
		\hline
		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 947       & 1,150 & N/A        & \begin{tabular}{@{}c@{}}DSP18x18s=14\end{tabular}\\
		\hline
		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 720       & 1475  & 163.827    & \begin{tabular}{@{}c@{}}DSP48E1s=7\end{tabular}  \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 720       & 1089  & 125.109    & \begin{tabular}{@{}c@{}}DSP48E1s=7\end{tabular}  \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 720       & 1503  & 161.577    & \begin{tabular}{@{}c@{}}DSP48E1s=7\end{tabular}  \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
