# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

Containers=lime_in_cont_ml605 lime_in lime_in_cont lime_inout_cont lime_split_cont \
            cstest_card
#           removed: zed_zipper_inout cstest_zed_zipper zed_zipper_inout_zipper
#                    - the 'zed_zipper' is unsupported
include $(OCPI_CDK_DIR)/include/hdl/hdl-assembly.mk
