# Copyright (c) 2009 Mercury Federal Systems.
# 
# This file is part of OpenCPI.
# 
# OpenCPI is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# OpenCPI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.

all: build

include ../MakeVars.cpi

TESTS_TO_BUILD_1 = $(dir $(wildcard */*/Makefile.cpi))
TESTS_TO_BUILD_2 = $(dir $(shell find . -name Makefile -print))

.PHONY: test
.EXPORT_ALL_VARIABLES:
RUN_VIA_MAKEFILE=1

build:
	for dir in $(TESTS_TO_BUILD_1) ; do \
		$(MAKE) -C $$dir -f Makefile.cpi || exit 1 ; \
	done
	for dir in $(TESTS_TO_BUILD_2) ; do \
		$(MAKE) -C $$dir -f Makefile || exit 1 ; \
	done

test:
	./run-all-tests

clean:
	for dir in $(TESTS_TO_BUILD_1) ; do \
		$(MAKE) -C $$dir -f Makefile.cpi clean || exit 1 ; \
	done
	for dir in $(TESTS_TO_BUILD_2) ; do \
		$(MAKE) -C $$dir -f Makefile clean || exit 1 ; \
	done

distclean: clean
	rm -rf log-*
