% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {4}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_adc}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_debug & ocpi\_endian & fifo\_depth \\
            \hline
            0             & false       & little       & 64 \\
            \hline
        \end{longtable}
\end{tiny}
