% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "ad9361\_adc"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 188             & 192        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 1536\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 218             & 196        & N/A              & \begin{tabular}{@{}l@{}}RAMB18E1: 1\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 237             & 299        & 262.123          & \begin{tabular}{@{}l@{}}RAM64M: 8\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 237             & 290        & 233.263          & \begin{tabular}{@{}l@{}}RAM64M: 8\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
