%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "ad9361_adc"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+ocpi_endian=little+
	\item \verb+ocpi_debug=false+
	\item \verb+fifo_depth=64+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions                      \\
		\hline
		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 187       & 185  & N/A        & N/A                                           \\
		\hline
		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 208       & 258  & 335.373    & \begin{tabular}{@{}c@{}}RAM64Ms=8\end{tabular}\\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 188       & 133  & 224.568    & N/A                                           \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 208       & 254  & 354.237    & \begin{tabular}{@{}c@{}}RAM64Ms=8\end{tabular}\\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
