% Generated on Fri Sep 28 16:14:12 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {4}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: lime\_tx}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_endian & ocpi\_debug & txen\_pin\_control\_p \\
            \hline
            0             & little       & false       & false \\
            \hline
            1             & little       & false       & true \\
            \hline
        \end{longtable}
\end{tiny}
