% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {4}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: lime\_tx}\\
        \hline
        \rowcolor{blue}
            Configuration & txen\_pin\_control\_p & ocpi\_endian & ocpi\_debug \\
            \hline
            0             & false                 & little       & false \\
            \hline
            1             & true                  & little       & false \\
            \hline
        \end{longtable}
\end{tiny}
