% Generated on Fri Sep 28 16:14:05 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {6}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: pr\_cordic}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_endian & DATA\_EXT & DATA\_WIDTH & STAGES & ocpi\_debug \\
            \hline
            0             & little       & 6         & 16          & 18     & false \\
            \hline
        \end{longtable}
\end{tiny}
