Workers = delayRcc delayRcc2
IncludeDirs=../foo
SourceFiles=foo.c
OCPI_DIR=../../../ocpi
# Set this if some of the xml files are elsewhere, like a spec file that is being
# shared with other implementers
include $(OCPI_DIR)/include/rcc/rcc-worker.mk
