% Generated on Fri Sep 28 16:14:02 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: mfsk\_mapper}\\
        \hline
        \rowcolor{blue}
            Configuration & M\_p & ocpi\_endian & DIN\_WIDTH\_p & ocpi\_debug \\
            \hline
            0             & 2    & little       & 16            & false \\
            \hline
        \end{longtable}
\end{tiny}
