% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: mfsk\_mapper}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_debug & ocpi\_endian & DIN\_WIDTH\_p & M\_p \\
            \hline
            0             & false       & little       & 16            & 2 \\
            \hline
            1             & false       & little       & 16            & 4 \\
            \hline
        \end{longtable}
\end{tiny}
