%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "mfsk_mapper"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+ocpi_endian=little+
	\item \verb+ocpi_debug=false+
	\item \verb+M_p=2+
	\item \verb+DIN_WIDTH_p=16+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 151       & 189  & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 137       & 464  & 303.306    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 150       & 144  & 201.654    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 139       & 464  & 331.455    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
