% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "ad9361\_adc\_ts"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 323             & 421        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 5760\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 359             & 508        & 196.967          & \begin{tabular}{@{}l@{}}RAMB36E1: 1\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 359             & 484        & 181.357          & \begin{tabular}{@{}l@{}}RAMB36E1: 1\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 353             & 393        & N/A              & \begin{tabular}{@{}l@{}}RAMB18E1: 1 \\ RAMB36E1: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
