% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "dc\_offset\_iq\_imbalance\_mixer\_cic\_dec\_timestamper"}\\
        \hline
        \rowcolor{blue}
            Container                                               & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_hpc\_LVDS\_ml605 & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 14277           & 19006      & 125.534          & \begin{tabular}{@{}l@{}}BUFGCTRL: 6 \\ BUFG: 6 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605 & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 14277           & 19006      & 125.534          & \begin{tabular}{@{}l@{}}BUFGCTRL: 6 \\ BUFG: 6 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 7992            & 11025      & 100.22           & \begin{tabular}{@{}l@{}}BUFGCTRL: 2 \\ BUFG: 2 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 9305            & 9597       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 2 \\ BUFG: 2 \\ RAMB36E1: 21 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_matchstiq\_z1                   & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 10359           & 10629      & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 2 \\ BUFG: 2 \\ RAMB36E1: 21 \\ DSP48E1: 15 \\ RAMB18E1: 2\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_hpc\_ml605              & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 14277           & 19006      & 125.534          & \begin{tabular}{@{}l@{}}BUFGCTRL: 6 \\ BUFG: 6 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_hsmc\_a\_alst4          & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 41362           & 27243      & N/A              & \begin{tabular}{@{}l@{}}DSP18: 26 \\ GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 498916 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_hsmc\_b\_alst4          & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 41362           & 27243      & N/A              & \begin{tabular}{@{}l@{}}DSP18: 26 \\ GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 498916 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_lpc\_ml605              & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 14277           & 19006      & 125.534          & \begin{tabular}{@{}l@{}}BUFGCTRL: 6 \\ BUFG: 6 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_lpc\_zed                & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 7992            & 11025      & 100.22           & \begin{tabular}{@{}l@{}}BUFGCTRL: 2 \\ BUFG: 2 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_lpc\_zed                & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 9305            & 9597       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 2 \\ BUFG: 2 \\ RAMB36E1: 21 \\ DSP48E1: 15\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
