% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: complex\_mixer}\\
        \hline
        \rowcolor{blue}
            Configuration & INPUT\_DATA\_WIDTH\_p & ocpi\_debug & VIVADO\_ILA\_p & CORDIC\_STAGES\_p & PEAK\_MONITOR\_p & NCO\_DATA\_WIDTH\_p & ocpi\_endian & CHIPSCOPE\_p \\
            \hline
            0             & 12                    & false       & false          & 16                & true             & 12                  & little       & false \\
            \hline
            1             & 16                    & false       & false          & 16                & true             & 16                  & little       & false \\
            \hline
            2             & 12                    & false       & true           & 16                & true             & 12                  & little       & false \\
            \hline
        \end{longtable}
\end{tiny}
