% Generated on Fri Sep 28 16:14:02 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: complex\_mixer}\\
        \hline
        \rowcolor{blue}
            Configuration & NCO\_DATA\_WIDTH\_p & PEAK\_MONITOR\_p & ocpi\_debug & CHIPSCOPE\_p & INPUT\_DATA\_WIDTH\_p & ocpi\_endian & VIVADO\_ILA\_p & CORDIC\_STAGES\_p \\
            \hline
            0             & 12                  & true             & false       & false        & 12                    & little       & false          & 16 \\
            \hline
            1             & 16                  & true             & false       & false        & 16                    & little       & false          & 16 \\
            \hline
            2             & 12                  & true             & false       & false        & 12                    & little       & true           & 16 \\
            \hline
        \end{longtable}
\end{tiny}
