% Generated on Fri Oct  5 08:45:51 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: complex\_mixer}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1214            & 2555       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1215            & 2816       & 222.207          & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1268            & 1742       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 8\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1452            & 3084       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1407            & 3319       & 165.044          & \begin{tabular}{@{}l@{}}DSP48E1: 8\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1468            & 1926       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 12\end{tabular} \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1216            & 2566       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1216            & 2820       & 222.207          & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1268            & 1742       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 8\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
