% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "complex\_mixer"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1384            & 1804       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 8\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1328            & 2695       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1325            & 2993       & 214.658          & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1325            & 2996       & 222.218          & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1584            & 1999       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 12\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1562            & 3219       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1517            & 3491       & 162.76           & \begin{tabular}{@{}l@{}}DSP48E1: 8\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1517            & 3491       & 165.044          & \begin{tabular}{@{}l@{}}DSP48E1: 8\end{tabular} \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1384            & 1804       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 8\end{tabular} \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1329            & 2689       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            2             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1326            & 2998       & 212.224          & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1326            & 3001       & 222.218          & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
