# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

# This library is for altera-supplied code that is not in cores and not in their core libraries
# that are automatically used.
OnlyTargets=stratix4
Imports=\
 $(OCPI_HDL_IMPORTS_DIR)/coregen/pcie_4243_hip_s4gx_gen2_x4_128/pcie_hip_s4gx_gen2_x4_128_examples/chaining_dma/pcie_hip_s4gx_gen2_x4_128_rs_hip.v \
 $(OCPI_HDL_IMPORTS_DIR)/coregen/pcie_4243_hip_s4gx_gen2_x4_128/pci_express_compiler-library/altpcie_reconfig_4sgx.v \
 $(OCPI_HDL_IMPORTS_DIR)/scripts/altera/cleaned_alst4/pll1.v
HdlNoLibraries=yes
include $(OCPI_CDK_DIR)/include/hdl/hdl-lib.mk # we are a library of primitives



