OCPI_DIR=../../../ocpi
# Which component libraries should be referenced to build this app?
OcpiLibraries=../../../components
XmlIncludeDirs += ../../platform
# For which containers should the runtime xml be generated?
# These (for now) just xml files containing HdlContainer elements.
Containers=testddcCont
#Target=xc5vlx50t-ff1136-1
Target=xc5vsx95t-ff1136-2
include $(OCPI_DIR)/include/hdl/hdl-app.mk
