#!/bin/bash
# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

trap "exit 99" TERM
export TOP_PID=$$

need() {
  eval VAL=\$$1
  if [ -z "${VAL}" ]; then
    echo "Need to set $1!"
    /usr/bin/kill -s TERM $TOP_PID
#  else
#    echo "cross-configure: $1 = ${VAL}"
  fi
}

need OCPI_CDK_DIR
need OCPI_TARGET_PLATFORM
# Before calling ocpitarget.sh, we want to force it into "bootstrap" mode. This will allow you to build an RPM for a
# platform that you don't have an RPM already installed for BUT have ANY RPM installed (e.g. only the base one)
export ORIG_OCPI_CDK=${OCPI_CDK_DIR}
export OCPI_CDK_DIR=`pwd`/bootstrap
source tools/cdk/scripts/ocpitarget.sh ${OCPI_TARGET_PLATFORM}
export OCPI_CDK_DIR=${ORIG_OCPI_CDK}

need OCPI_CROSS_BUILD_BIN_DIR
need OCPI_CROSS_HOST
need OCPI_TARGET_HOST

export PATH=${OCPI_CROSS_BUILD_BIN_DIR}:${PATH}
export CROSS_CONFIGURE_RUNNING=1
./ocpi-configure --with-cross-dir=${OCPI_CROSS_BUILD_BIN_DIR} --host=${OCPI_CROSS_HOST} --with-cross-host=${OCPI_CROSS_HOST} --with-target=${OCPI_TARGET_HOST} --with-target-platform=${OCPI_TARGET_PLATFORM} "$@"
