% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {6}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: lime\_dac}\\
        \hline
        \rowcolor{blue}
            Configuration & USE\_CTL\_CLK\_p & DRIVE\_CLK\_p & ocpi\_endian & USE\_CLK\_IN\_p & ocpi\_debug \\
            \hline
            0             & 0                & 1             & little       & 1               & false \\
            \hline
        \end{longtable}
\end{tiny}
