% Generated on Fri Sep 28 16:14:11 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {6}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: lime\_dac}\\
        \hline
        \rowcolor{blue}
            Configuration & USE\_CLK\_IN\_p & ocpi\_endian & ocpi\_debug & DRIVE\_CLK\_p & USE\_CTL\_CLK\_p \\
            \hline
            0             & 1               & little       & false       & 1             & 0 \\
            \hline
        \end{longtable}
\end{tiny}
