%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "lime_dac"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+ocpi_endian=little+
	\item \verb+ocpi_debug=false+
	\item \verb+DRIVE_CLK_p=1+
	\item \verb+USE_CTL_CLK_p=0+
	\item \verb+USE_CLK_IN_p=1+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions                      \\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 151       & 179  & N/A        & N/A                                           \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 172       & 316  & 444.109    & \begin{tabular}{@{}c@{}}RAM64Ms=8\end{tabular}\\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 152       & 135  & 309.215    & N/A                                           \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 172       & 314  & 547.555    & \begin{tabular}{@{}c@{}}RAM64Ms=8\end{tabular}\\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
