% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: cic\_dec\_ts}\\
        \hline
        \rowcolor{blue}
            Configuration & M & N & R & ACC\_WIDTH \\
            \hline
            0             & 1 & 3 & 8 & 25 \\
            \hline
        \end{longtable}
\end{tiny}
