# Put Makefile customizations for worker jm.rcc here:
SourceFiles = genmat.cilk
Path = /work/kulp/cilk/cilk/lib64
#Libraries =   cilkrts cilkutil
LinkFiles = genmat.o


include $(OCPI_CDK_DIR)/include/worker.mk


