# Setup to build based on Xilinx tools
ifndef OCPI_XILINX_DIR
  export OCPI_XILINX_DIR:=/opt/Xilinx
endif
ifndef OCPI_XILINX_VERSION
 export OCPI_XILINX_VERSION:=14.7
endif
ifndef OCPI_XILINX_LICENSE_FILE
  export OCPI_XILINX_LICENSE_FILE=$(OCPI_XILINX_DIR)/Xilinx-License.lic
endif
export OCPI_XILINX_TOOLS_DIR:=$(OCPI_XILINX_DIR)/$(OCPI_XILINX_VERSION)/ISE_DS
ifeq ($(wildcard $(OCPI_XILINX_TOOLS_DIR)),)
  export OCPI_XILINX_TOOLS_DIR:=$(OCPI_XILINX_DIR)/$(OCPI_XILINX_VERSION)/LabTools
endif
export OCPI_XILINX_EDK_DIR:=$(OCPI_XILINX_DIR)/$(OCPI_XILINX_VERSION)/ISE_DS/EDK
export OCPI_VIVADO_TOOLS_DIR:=$(OCPI_XILINX_DIR)/Vivado/$(OCPI_VIVADO_VERSION)
