%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "capture"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions                        \\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 848       & 911  & N/A        & N/A                                             \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 552       & 1198 & 250.785    & N/A                                             \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 533       & 959  & 208.725    & \begin{tabular}{@{}c@{}}RAMB36E1s=3\end{tabular}\\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 552       & 1163 & 337.644    & N/A                                             \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
