% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "phase\_to\_amp\_cordic"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1121            & 1419       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 8\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1105            & 2380       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 2\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1058            & 2466       & 162.602          & \begin{tabular}{@{}l@{}}DSP48E1: 4\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1058            & 2466       & 164.88           & \begin{tabular}{@{}l@{}}DSP48E1: 4\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1389            & 1805       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 8\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1367            & 3012       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 2\end{tabular} \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1322            & 3090       & 162.602          & \begin{tabular}{@{}l@{}}DSP48E1: 4\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1322            & 3090       & 164.88           & \begin{tabular}{@{}l@{}}DSP48E1: 4\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
