# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

Core=dram_v6_mig34
Top=v6_mig33
ExcludeTargets=
OnlyTargets=virtex6
SourceFiles=\
 mig_v3_4_patch20110331.v\
 iodelay_ctrl_eco20100428.v\
 arb_mux.v\
 arb_row_col.v\
 arb_select.v\
 bank_cntrl.v\
 bank_common.v\
 bank_compare.v\
 bank_mach.v\
 bank_queue.v\
 bank_state.v\
 col_mach.v\
 mc.v\
 rank_cntrl.v\
 rank_common.v\
 rank_mach.v\
 round_robin_arb.v\
 ecc_buf.v\
 ecc_dec_fix.v\
 ecc_gen.v\
 ecc_merge_enc.v\
 clk_ibuf.v\
 ddr2_ddr3_chipscope.v\
 infrastructure.v\
 mem_intfc.v\
 memc_ui_top.v\
 circ_buffer.v\
 phy_ck_iob.v\
 phy_clock_io.v\
 phy_control_io.v\
 phy_data_io.v\
 phy_dly_ctrl.v\
 phy_dm_iob.v\
 phy_dq_iob.v\
 phy_dqs_iob.v\
 phy_init.v\
 phy_pd.v\
 phy_pd_top.v\
 phy_rdclk_gen.v\
 phy_rdctrl_sync.v\
 phy_rddata_sync.v\
 phy_rdlvl.v\
 phy_read.v\
 phy_top.v\
 phy_write.v\
 phy_wrlvl.v\
 rd_bitslip.v\
 ui_cmd.v\
 ui_rd_data.v\
 ui_top.v\
 ui_wr_data.v\
# end of files
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk
