#!/bin/sh -f
esn=$1
out=$2
shift
shift
. $OCPI_XILINX_TOOLS_DIR/settings64.sh 2>$out 1>&2
echo listusbcables | \
 impact -batch 2>>$out  | \
 grep '^port=' | \
 sed 's/port=\(.*\), *\(.*\)/\1 \2/' | \
 sed 's/Legacy Cable.*/esn=0123456789ABCD/' | \
 grep $esn | \
 sed 's/^\([^ ]*\).*$/\1/'
