#!/bin/sh
# bitgen option.userid...biggen_bin.ut "userid on line 21 - feed5200".

if [[ $# != 2 ]]; then
  echo Usage is: `basename $0` usb_port part 1>&2
  echo This is an internal script that takes a usb port and a part, and finds the 1>&2
  echo JTAG position corresponding to that part. 1>&2
  exit 1
fi
port=`echo $1 | tr A-Z a-z`
temp=/tmp/cpibitstream$$
tlog=$temp.1
tmp=$temp.2
function good {
  rm -f $temp.*
  exit 0
}
function bad {
  rm -f $tmp
  echo Look at $tlog for details. 1>&2
  exit 1
}
#part=${1:-xc5vlx50t}
#pos=${2:-1}
#echo part "$part" pos "$pos" port "$port"
#echo PORT IS $port
imp="$OCPI_XILINX_TOOLS_DIR/ISE/bin/lin64/impact -batch"
for pp in 1 2 3 4 5 6 7 8 9; do
  echo setMode -bs/setCable -p $port/identify/readidcode -p $pp | tr / \\n | $imp  2> $tlog 1>&2
  last=$?
  #echo status:$? $tlog 
  if test $last == 0; then
    ed $tlog <<EOF > /dev/null 2>&1
      $
      ?IDCODE?+
      s/^.*Xilinx \([^,]*\),.*\$/\1/p
      1,-d
      2,\$d
      w $tmp
EOF
    if [[ `cat $tmp` == $2 ]]; then
       echo $pp
       good
    fi
  else
    echo Error: did not find part $2 in the jtag chain for port $port. 1>&2
    echo Try running probeUsb 1>&2
    bad    
  fi
done
echo Too many positions on jtag. 1>&2

