#!/bin/sh --noprofile
if [[ $# < 4 ]]; then
    echo Usage is: "$0:t" bit_file PCI_device part-name $#
    echo '  'An example is '(for an ML555)' is:
    echo '    'loadBitStreamOnPlatform testbias-ml555.bit.gz 0000:02:00.0 xc5vlx50t
    echo '  To find the PCI devices (available containers),' use the '"sudo -E ocfrp_check"' command.
    echo '    'With ocfrp_check, OpenCPI boards with valid bitstreams look like:
    echo '    'Found an OpenOCPI FPGA at PCI 0000:04:00.0 ...'
    echo '  'Use "probeXilinxUsb all" to find out usb port names, JTAG Cable ESNs, parts and jtag positions.
    echo '  'This loading script relies on a database to correlate JTAG Cable ESNs and PCI devices'
    echo '  'If it doesn\'t find the part, it will say so and fail.
    echo '  'For now, you must select the correct USB port and part for the device.
    exit 1
fi
tmp=/tmp/ocpibitstream$$
port=`echo listusbcables | $OCPI_XILINX_TOOLS_DIR/ISE/bin/lin64/impact -batch 2> $tmp | grep '^port=' | sed 's/port=\(.*\), *esn=\(.*\)/\1 \2/' | grep $5 | sed 's/^\([^ ]*\).*$/\1/'`
loadBitStream $1 $2 $port $4
exit 0