#!/bin/csh -f

set log=testDMA$$.log
echo Start with $argv >& $log
echo Log is: `pwd`/$log
set tree=$OCPI_BASE_DIR
set cmd="sudo -E LD_LIBRARY_PATH=$tree/lib/linux-x86_64-bin:/usr/local $tree/core/container/hdl_container/linux-x86_64-bin/testRpl"
#set cmd="sudo -E testRpl"

if ($#argv == 0) then
   echo Usage is: testDMA "<DP-roles> <nbufs> <message-sizes> <message-counts> [bd1] [bd2]"
   echo Example: testDMA '"f" "1 2" "0 16" "1 1000"'
   exit 1
endif
if ($#argv >= 5) then
   set args="$argv[5-]"
else
   set args=""
endif
foreach r1i ($1)
  foreach r3o ($1)
    foreach n0o ($2)
      foreach n1i ($2)
        foreach n3o ($2)
          foreach n0i ($2)
            foreach I ($3)
              foreach i ($4)
                if ($#argv == 6) then
		  # two boards
		  foreach r6o ($1)
                    foreach n4i ($2)
		      foreach n6o ($2)
		        set params="-r1i$r1i -r3om -N0o $n0o -N1i $n1i -N3o $n3o -N0i $n0i -I $I -i $i -N4i $n4i -r6o$r6o -N6o $n6o"
			echo -n For $params $args ..." "
		        echo For $params $args >>& $log
		        $cmd $params $args >>& $log
			if ($status != 0) then
			  echo FAILED
			  exit 1
			else
			  echo SUCCEEDED
			endif
		      end
		    end
		  end
		else
		  set params="-r1i$r1i -r3o$r3o -N0o $n0o -N1i $n1i -N3o $n3o -N0i $n0i -I $I -i $i"
		  echo -n For $params $args ..." "
		  echo For $params $args >>& $log
                  $cmd $params $args >>& $log
		  if ($status != 0) then
		    echo FAILED
		    exit 1
		  else
		    echo SUCCEEDED
		  endif
		  if ($status != 0) exit
                endif
end
end
end
end
end
end
end
end
echo "testDMA done"
