# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

Containers= \
	cnt_1rx_0tx_thruasm_fmcomms_2_3_hpc_LVDS_ml605 \
	cnt_1rx_0tx_thruasm_fmcomms_2_3_lpc_LVDS_ml605 \
	cnt_1rx_0tx_thruasm_fmcomms_2_3_lpc_LVDS_zed

#VivadoExtraOptions_synth=" -<myoption1> -<myoption2> "
#VivadoExtraOptions_impl_opt=" -<myoption1> -<myoption2> "
#VivadoExtraOptions_impl_place=" -<myoption1> -<myoption2> "
#VivadoExtraOptions_impl_post_place_phys_opt=" -<myoption1> -<myoption2> "
#VivadoExtraOptions_impl_route=" -<myoption1> -<myoption2> "
#VivadoExtraOptions_impl_post_route_phys_opt=" -<myoption1> -<myoption2> "
#VivadoExtraOptions_impl_timing=" -<myoption1> -<myoption2> "
#VivadoExtraOptions_impl_bit=" -<myoption1> -<myoption2> "
#VivadoPostPlaceOpt=true
#VivadoPostRouteOpt=true

DefaultContainers=
ExcludePlatforms=isim modelsim xsim
include $(OCPI_CDK_DIR)/include/hdl/hdl-assembly.mk
