% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "ad9361\_1r1t\_test\_adc\_asm"}\\
        \hline
        \rowcolor{blue}
            Container                                               & OCPI Platform & OCPI Target & Tool   & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_hpc\_LVDS\_ml605 & ml605         & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 10588           & 21064      & 125.188          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605 & ml605         & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 10588           & 21064      & 125.188          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed\_ise      & zynq\_ise   & ISE    & 14.7    & 7z020clg484-1    & 4255            & 13340      & 100.02           & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed           & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 5703            & 12331      & 350.14           & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 18 \\ ODDR: 1 \\ BUFR: 2 \\ RAMB18E1: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
