EXTRA_INCLUDES=\
  $(ACE_ROOT) \
  $(ACE_ROOT)/TAO \
  $(ACE_ROOT)/TAO/tao \
  $(ACE_ROOT)/TAO/TAO_IDL/include \
  $(ACE_ROOT)/TAO/TAO_IDL/be_include \
  $(ACE_ROOT)/TAO/orbsvcs/IFR_Service \
  $(ACE_ROOT)/TAO/orbsvcs

include ../../../../../Makefile.cpi.for-src
