% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "pattern\_v2"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 966             & 640        & N/A              & N/A \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 963             & 650        & N/A              & N/A \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 958             & 699        & 325.573          & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 961             & 699        & 265.104          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
