Libraries=$(foreach l,bsv ocpi,$(OCPI_DIR)/lib/hdl/$(l))
# Force the target.  Don't build for any others
# override Target=xc5vsx95t-2-ff1136
OcpiCores=$(OCPI_DIR)/lib/hdl/xfft_v7_1
include $(OCPI_DIR)/include/hdl/hdl-worker.mk
