% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {6}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: zero\_padding}\\
        \hline
        \rowcolor{blue}
            Configuratio & MAX\_NUM\_ZEROS\_p & ODATA\_WIDTH\_p & ocpi\_endian & IDATA\_WIDTH\_p & ocpi\_debug \\
            \hline
            0            & 255                & 8               & little       & 8               & false \\
            \hline
            1            & 255                & 16              & little       & 8               & false \\
            \hline
            2            & 255                & 32              & little       & 8               & false \\
            \hline
            3            & 255                & 64              & little       & 8               & false \\
            \hline
            4            & 255                & 8               & little       & 16              & false \\
            \hline
            5            & 255                & 16              & little       & 16              & false \\
            \hline
            6            & 255                & 32              & little       & 16              & false \\
            \hline
            7            & 255                & 64              & little       & 16              & false \\
            \hline
            8            & 255                & 8               & little       & 32              & false \\
            \hline
            9            & 255                & 16              & little       & 32              & false \\
            \hline
            10           & 255                & 32              & little       & 32              & false \\
            \hline
            11           & 255                & 64              & little       & 32              & false \\
            \hline
            12           & 255                & 8               & little       & 64              & false \\
            \hline
            13           & 255                & 16              & little       & 64              & false \\
            \hline
            14           & 255                & 32              & little       & 64              & false \\
            \hline
            15           & 255                & 64              & little       & 64              & false \\
            \hline
        \end{longtable}
\end{tiny}
