% Generated on Fri Sep 28 16:14:07 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {6}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: zero\_padding}\\
        \hline
        \rowcolor{blue}
            Configuration & MAX\_NUM\_ZEROS\_p & ocpi\_endian & IDATA\_WIDTH\_p & ODATA\_WIDTH\_p & ocpi\_debug \\
            \hline
            0             & 255                & little       & 8               & 8               & false \\
            \hline
            1             & 255                & little       & 8               & 16              & false \\
            \hline
            2             & 255                & little       & 8               & 32              & false \\
            \hline
            3             & 255                & little       & 8               & 64              & false \\
            \hline
            4             & 255                & little       & 16              & 8               & false \\
            \hline
            5             & 255                & little       & 16              & 16              & false \\
            \hline
            6             & 255                & little       & 16              & 32              & false \\
            \hline
            7             & 255                & little       & 16              & 64              & false \\
            \hline
            8             & 255                & little       & 32              & 8               & false \\
            \hline
            9             & 255                & little       & 32              & 16              & false \\
            \hline
            10            & 255                & little       & 32              & 32              & false \\
            \hline
            11            & 255                & little       & 32              & 64              & false \\
            \hline
            12            & 255                & little       & 64              & 8               & false \\
            \hline
            13            & 255                & little       & 64              & 16              & false \\
            \hline
            14            & 255                & little       & 64              & 32              & false \\
            \hline
            15            & 255                & little       & 64              & 64              & false \\
            \hline
        \end{longtable}
\end{tiny}
