% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "zero\_padding"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 275             & 322        & N/A              & N/A \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 272             & 329        & N/A              & N/A \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 267             & 448        & 197.2            & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 267             & 448        & 183.942          & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 274             & 320        & N/A              & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 271             & 320        & N/A              & N/A \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 266             & 443        & 197.668          & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 266             & 443        & 184.349          & N/A \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 273             & 321        & N/A              & N/A \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 270             & 317        & N/A              & N/A \\
            \hline
            2             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 263             & 439        & 198.373          & N/A \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 263             & 439        & 184.894          & N/A \\
            \hline
            3             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 272             & 315        & N/A              & N/A \\
            \hline
            3             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 269             & 295        & N/A              & N/A \\
            \hline
            3             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 261             & 439        & 216.92           & N/A \\
            \hline
            3             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 261             & 440        & 203.915          & N/A \\
            \hline
            4             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 325             & 331        & N/A              & N/A \\
            \hline
            4             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 322             & 366        & N/A              & N/A \\
            \hline
            4             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 317             & 493        & 197.2            & N/A \\
            \hline
            4             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 317             & 493        & 183.942          & N/A \\
            \hline
            5             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 324             & 329        & N/A              & N/A \\
            \hline
            5             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 321             & 358        & N/A              & N/A \\
            \hline
            5             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 316             & 488        & 197.668          & N/A \\
            \hline
            5             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 316             & 488        & 184.349          & N/A \\
            \hline
            6             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 323             & 329        & N/A              & N/A \\
            \hline
            6             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 320             & 354        & N/A              & N/A \\
            \hline
            6             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 313             & 483        & 198.373          & N/A \\
            \hline
            6             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 313             & 484        & 184.894          & N/A \\
            \hline
            7             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 322             & 323        & N/A              & N/A \\
            \hline
            7             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 319             & 332        & N/A              & N/A \\
            \hline
            7             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 311             & 511        & 216.92           & N/A \\
            \hline
            7             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 311             & 484        & 196.361          & N/A \\
            \hline
            8             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 427             & 324        & N/A              & N/A \\
            \hline
            8             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 424             & 438        & N/A              & N/A \\
            \hline
            8             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 419             & 588        & 190.636          & N/A \\
            \hline
            8             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 419             & 588        & 180.031          & N/A \\
            \hline
            9             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 426             & 322        & N/A              & N/A \\
            \hline
            9             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 423             & 426        & N/A              & N/A \\
            \hline
            9             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 418             & 577        & 190.636          & N/A \\
            \hline
            9             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 418             & 572        & 180.031          & N/A \\
            \hline
            10            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 425             & 322        & N/A              & N/A \\
            \hline
            10            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 422             & 424        & N/A              & N/A \\
            \hline
            10            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 415             & 568        & 190.636          & N/A \\
            \hline
            10            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 415             & 568        & 180.031          & N/A \\
            \hline
            11            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 424             & 316        & N/A              & N/A \\
            \hline
            11            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 421             & 403        & N/A              & N/A \\
            \hline
            11            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 413             & 556        & 193.028          & N/A \\
            \hline
            11            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 413             & 556        & 182.229          & N/A \\
            \hline
            12            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 633             & 337        & N/A              & N/A \\
            \hline
            12            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 630             & 582        & N/A              & N/A \\
            \hline
            12            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 625             & 766        & 197.707          & N/A \\
            \hline
            12            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 625             & 766        & 184.383          & N/A \\
            \hline
            13            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 632             & 335        & N/A              & N/A \\
            \hline
            13            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 629             & 578        & N/A              & N/A \\
            \hline
            13            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 624             & 755        & 198.098          & N/A \\
            \hline
            13            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 624             & 750        & 184.723          & N/A \\
            \hline
            14            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 631             & 335        & N/A              & N/A \\
            \hline
            14            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 628             & 570        & N/A              & N/A \\
            \hline
            14            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 621             & 745        & 198.373          & N/A \\
            \hline
            14            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 621             & 745        & 184.894          & N/A \\
            \hline
            15            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 630             & 330        & N/A              & N/A \\
            \hline
            15            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 627             & 549        & N/A              & N/A \\
            \hline
            15            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 619             & 733        & 200.04           & N/A \\
            \hline
            15            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 619             & 733        & 186.898          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
