% Generated on Fri Oct  5 08:45:57 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: zero\_padding}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 186             & 177        & N/A              & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 181             & 254        & 282.685          & N/A \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 187             & 238        & N/A              & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 186             & 177        & N/A              & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 181             & 254        & 282.685          & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 187             & 238        & N/A              & N/A \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 186             & 177        & N/A              & N/A \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 181             & 254        & 282.685          & N/A \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 187             & 238        & N/A              & N/A \\
            \hline
            3             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 186             & 177        & N/A              & N/A \\
            \hline
            3             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 181             & 254        & 282.685          & N/A \\
            \hline
            3             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 187             & 238        & N/A              & N/A \\
            \hline
            4             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 220             & 197        & N/A              & N/A \\
            \hline
            4             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 215             & 281        & 282.685          & N/A \\
            \hline
            4             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 221             & 247        & N/A              & N/A \\
            \hline
            5             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 220             & 197        & N/A              & N/A \\
            \hline
            5             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 215             & 281        & 282.685          & N/A \\
            \hline
            5             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 221             & 247        & N/A              & N/A \\
            \hline
            6             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 220             & 197        & N/A              & N/A \\
            \hline
            6             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 215             & 281        & 282.685          & N/A \\
            \hline
            6             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 221             & 247        & N/A              & N/A \\
            \hline
            7             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 220             & 197        & N/A              & N/A \\
            \hline
            7             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 215             & 281        & 282.685          & N/A \\
            \hline
            7             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 221             & 247        & N/A              & N/A \\
            \hline
            8             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 288             & 236        & N/A              & N/A \\
            \hline
            8             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 283             & 335        & 282.685          & N/A \\
            \hline
            8             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 289             & 272        & N/A              & N/A \\
            \hline
            9             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 288             & 236        & N/A              & N/A \\
            \hline
            9             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 283             & 335        & 282.685          & N/A \\
            \hline
            9             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 289             & 272        & N/A              & N/A \\
            \hline
            10            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 288             & 236        & N/A              & N/A \\
            \hline
            10            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 283             & 335        & 282.685          & N/A \\
            \hline
            10            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 289             & 272        & N/A              & N/A \\
            \hline
            11            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 288             & 236        & N/A              & N/A \\
            \hline
            11            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 283             & 335        & 282.685          & N/A \\
            \hline
            11            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 289             & 272        & N/A              & N/A \\
            \hline
            12            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 424             & 315        & N/A              & N/A \\
            \hline
            12            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 419             & 442        & 282.685          & N/A \\
            \hline
            12            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 425             & 316        & N/A              & N/A \\
            \hline
            13            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 424             & 315        & N/A              & N/A \\
            \hline
            13            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 419             & 442        & 282.685          & N/A \\
            \hline
            13            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 425             & 316        & N/A              & N/A \\
            \hline
            14            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 424             & 315        & N/A              & N/A \\
            \hline
            14            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 419             & 442        & 282.685          & N/A \\
            \hline
            14            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 425             & 316        & N/A              & N/A \\
            \hline
            15            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 424             & 315        & N/A              & N/A \\
            \hline
            15            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 419             & 442        & 282.685          & N/A \\
            \hline
            15            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 425             & 316        & N/A              & N/A \\
            \hline
        \end{longtable}
\end{tiny}
