%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "zero_padding"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+IDATA_WIDTH_p=8+
	\item \verb+ocpi_debug=false+
	\item \verb+ODATA_WIDTH_p=8+
	\item \verb+MAX_NUM_ZEROS_p=255+
	\item \verb+ocpi_endian=little+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 187       & 238  & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 181       & 254  & 282.685    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 186       & 177  & 201.369    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 181       & 254  & 306.560    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
%\textbf{Worker Build Configuration ``1'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=8+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=16+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``1''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 187       & 238  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 181       & 254  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 186       & 177  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 181       & 254  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``2'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=8+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=32+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``2''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 187       & 238  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 181       & 254  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 186       & 177  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 181       & 254  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``3'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=8+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=64+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``3''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 187       & 238  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 181       & 254  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 186       & 177  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 181       & 254  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``4'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=16+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=8+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``4''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 221       & 247  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 215       & 281  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 220       & 197  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 215       & 281  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``5'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=16+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=16+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``5''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 221       & 247  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 215       & 281  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 220       & 197  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 215       & 281  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``6'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=16+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=32+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``6''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 221       & 247  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 215       & 281  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 220       & 197  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 215       & 281  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``7'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=16+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=64+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``7''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 221       & 247  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 215       & 281  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 220       & 197  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 215       & 281  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``8'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=32+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=8+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``8''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 289       & 272  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 283       & 335  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 288       & 236  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 283       & 335  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``9'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=32+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=16+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``9''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 289       & 272  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 283       & 335  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 288       & 236  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 283       & 335  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``10'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=32+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=32+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``10''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 289       & 272  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 283       & 335  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 288       & 236  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 283       & 335  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``11'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=32+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=64+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``11''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 289       & 272  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 283       & 335  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 288       & 236  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 283       & 335  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``12'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=64+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=8+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``12''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 425       & 316  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 419       & 442  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 424       & 315  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 419       & 442  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``13'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=64+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=16+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``13''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 425       & 316  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 419       & 442  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 424       & 315  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 419       & 442  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``14'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=64+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=32+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``14''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 425       & 316  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 419       & 442  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 424       & 315  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 419       & 442  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``15'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+IDATA_WIDTH_p=64+
%	\item \verb+ocpi_debug=false+
%	\item \verb+ODATA_WIDTH_p=64+
%	\item \verb+MAX_NUM_ZEROS_p=255+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``15''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 425       & 316  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 419       & 442  & 282.685    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 424       & 315  & 201.369    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 419       & 442  & 306.560    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
