# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

Core=fft_v5_4k_strm_nat
Top=xfft_v7_1
ExcludeTargets=
OnlyTargets=virtex5 isim xsim
SourceFiles=\
 xfft_v7_1.v\
# end of files
PreBuiltCore=xfft_v7_1.ngc
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk
