% Generated on Fri Sep 28 16:14:11 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: ad9361\_dac}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers       & LUTs       & \multicolumn{2}{c|}{Fmax (MHz) (Typ)} & Memory/Special           \\
        \rowcolor{blue}
                          &             &         &         &                  & (Typ)           & (Typ)      & \multicolumn{2}{c|}{}               & Functions                \\
            \hline
        \rowcolor{blue}
                          &             &         &         &                  &                 &            & control plane & dev\_dac.dac\_clk &                          \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 235             & 225        & 186              & 232 & \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 232             & 315        & N/A              & & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 254             & 371        & 322.373          & 383.877 & \begin{tabular}{@{}l@{}}RAM64M: 8\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
