%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "gps_uart"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 261       & 337  & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 161       & 234  & 285.584    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 251       & 291  & 228.415    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 161       & 234  & 349.809    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
