% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "pattern"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 1112            & 1479       & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 164412\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 806             & 1746       & N/A              & \begin{tabular}{@{}l@{}}RAMB36E1: 5\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 793             & 1961       & 305.479          & \begin{tabular}{@{}l@{}}RAMB36E1: 5\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 793             & 1979       & 240.938          & \begin{tabular}{@{}l@{}}RAMB36E1: 5\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
