% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: fifo}\\
        \hline
        \rowcolor{blue}
            Configuration & FIFO\_DEPTH\_p & ocpi\_debug & ocpi\_endian & ZLM\_WHEN\_ONESHOT\_DONE\_p \\
            \hline
            0             & 8192           & false       & little       & false \\
            \hline
            1             & 8192           & false       & little       & true \\
            \hline
        \end{longtable}
\end{tiny}
