% Generated on Fri Sep 28 16:14:09 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: fifo}\\
        \hline
        \rowcolor{blue}
            Configuration & FIFO\_DEPTH\_p & ZLM\_WHEN\_ONESHOT\_DONE\_p & ocpi\_endian & ocpi\_debug \\
            \hline
            0             & 8192           & false                       & little       & false \\
            \hline
            1             & 8192           & true                        & little       & false \\
            \hline
        \end{longtable}
\end{tiny}
