% Generated on Fri Oct  5 08:45:57 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: fifo}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 370             & 7913       & N/A              & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 191             & 8032       & 267.551          & \begin{tabular}{@{}l@{}}RAM64M: 1536\end{tabular} \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 286             & 344        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 278494\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 409             & 7989       & N/A              & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 191             & 8035       & 253.615          & \begin{tabular}{@{}l@{}}RAM64M: 1536\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 286             & 348        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 278494\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
