% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "fifo"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 436             & 385        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 286685\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 550             & 8142       & N/A              & N/A \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 328             & 8215       & 307.39           & \begin{tabular}{@{}l@{}}RAM64M: 1536\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 329             & 8221       & 254.738          & \begin{tabular}{@{}l@{}}RAM64M: 1536\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 436             & 473        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 286685\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 550             & 8152       & N/A              & N/A \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 328             & 8218       & 307.39           & \begin{tabular}{@{}l@{}}RAM64M: 1536\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 328             & 8257       & 253.639          & \begin{tabular}{@{}l@{}}RAM64M: 1536\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
