% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {4}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_config\_ts}\\
        \hline
        \rowcolor{blue}
            Configuration & pin\_control\_p & ocpi\_debug & ocpi\_endian \\
            \hline
            0             & true            & false       & little \\
            \hline
        \end{longtable}
\end{tiny}
