% Generated on Fri Sep 28 16:14:11 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {4}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_dac}\\
        \hline
        \rowcolor{blue}
            Configuration & fifo\_depth & ocpi\_endian & ocpi\_debug \\
            \hline
            0             & 64          & little       & false \\
            \hline
        \end{longtable}
\end{tiny}
