% Generated on Fri Oct  5 08:45:59 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: ad9361\_dac}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 235             & 225        & N/A              & \begin{tabular}{@{}l@{}}RAMB18E1: 1\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 254             & 371        & 322.373          & \begin{tabular}{@{}l@{}}RAM64M: 8\end{tabular} \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 232             & 315        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 1536\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
