% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "ad9361\_dac"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 301             & 321        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 1536\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 304             & 320        & N/A              & \begin{tabular}{@{}l@{}}RAMB18E1: 1\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 321             & 556        & 305.448          & \begin{tabular}{@{}l@{}}RAM64M: 8\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 321             & 556        & 284.91           & \begin{tabular}{@{}l@{}}RAM64M: 8\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
