% Generated on Fri Oct  5 08:48:27 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: testbias5}\\
        \hline
        \rowcolor{blue}
            Container & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base      & e3xx          & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 9105            & 7751       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 16681           & 22680      & 125.203          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            base      & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 9151            & 7694       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 57985           & 34882      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 762894 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            base      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 8788            & 7505       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
