Core=dram_v5_mig34
Top=v5_mig34
ExcludeTargets=
OnlyTargets=virtex5
SourceFiles=\
 ddr2_ctrl.v\
 ddr2_mem_if_top.v\
 ddr2_phy_calib.v\
 ddr2_phy_ctl_io.v\
 ddr2_phy_dm_iob.v\
 ddr2_phy_dq_iob.v\
 ddr2_phy_dqs_iob.v\
 ddr2_phy_init.v\
 ddr2_phy_io.v\
 ddr2_phy_top.v\
 ddr2_phy_write.v\
 ddr2_top.v\
 ddr2_usr_addr_fifo.v\
 ddr2_usr_rd.v\
 ddr2_usr_top.v\
 ddr2_usr_wr.v\
 ddr2_idelay_ctrl_eco20100514.v\
 ddr2_infrastructure_eco20100512.v\
 v5_mig34.v\
# end of files
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk
