OCPI_DIR=../../../ocpi
CoreBlackBoxFile=$(Core)_bb.v
Targets=xc5vsx95t-2-ff1136 xc5vlx50t-1-ff1136 xc6vlx240t-1-ff1156 
DontBuildCores=yes # suppress normal rules to build the core from source files
include $(OCPI_DIR)/include/hdl/hdl-core.mk
