% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {4}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_config}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_debug & pin\_control\_p & ocpi\_endian \\
            \hline
            0             & false       & true            & little \\
            \hline
        \end{longtable}
\end{tiny}
