%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "ad9361_config"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 70        & 149  & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 66        & 193  & 327.869    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 67        & 113  & 230.894    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 66        & 193  & 348.554    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
