% Generated on Fri Sep 28 16:14:11 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {4}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: lime\_dac\_ts}\\
        \hline
        \rowcolor{blue}
            Configuration & USE\_CLK\_IN\_p & FRACTION\_WIDTH\_p & USE\_CTL\_CLK\_p \\
            \hline
            0             & 1               & 32                 & 0 \\
            \hline
            1             & 1               & 26                 & 0 \\
            \hline
        \end{longtable}
\end{tiny}
