% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {4}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: lime\_dac\_ts}\\
        \hline
        \rowcolor{blue}
            Configuration & FRACTION\_WIDTH\_p & USE\_CTL\_CLK\_p & USE\_CLK\_IN\_p \\
            \hline
            0             & 32                 & 0                & 1 \\
            \hline
            1             & 26                 & 0                & 1 \\
            \hline
        \end{longtable}
\end{tiny}
