%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "lime_dac_ts"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+DRIVE_CLK_p=1+
	\item \verb+ocpi_endian=little+
	\item \verb+USE_CTL_CLK_p=0+
	\item \verb+USE_CLK_IN_p=1+
	\item \verb+SECONDS_WIDTH_p=32+
	\item \verb+ocpi_debug=false+
	\item \verb+FRACTION_WIDTH_p=32+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 310       & 352  & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 305       & 476  & 351.744    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 313       & 247  & 283.126    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 305       & 477  & 431.537    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
%\textbf{Worker Build Configuration ``1'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DRIVE_CLK_p=1+
%	\item \verb+ocpi_endian=little+
%	\item \verb+USE_CTL_CLK_p=0+
%	\item \verb+USE_CLK_IN_p=1+
%	\item \verb+SECONDS_WIDTH_p=32+
%	\item \verb+ocpi_debug=false+
%	\item \verb+FRACTION_WIDTH_p=26+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``1''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 304       & 339  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 299       & 470  & 351.744    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 307       & 244  & 283.126    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 299       & 471  & 431.537    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
