% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "lime\_dac\_ts"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 472             & 474        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 1664\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 477             & 433        & N/A              & \begin{tabular}{@{}l@{}}ODDR: 1 \\ RAMB18E1: 1\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 464             & 688        & 331.035          & \begin{tabular}{@{}l@{}}ODDR: 1\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 464             & 670        & 262.344          & \begin{tabular}{@{}l@{}}ODDR: 1\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 466             & 468        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 1664\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 471             & 428        & N/A              & \begin{tabular}{@{}l@{}}ODDR: 1 \\ RAMB18E1: 1\end{tabular} \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 458             & 682        & 331.035          & \begin{tabular}{@{}l@{}}ODDR: 1\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 458             & 664        & 262.344          & \begin{tabular}{@{}l@{}}ODDR: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
