SourceFiles=	i2c_pkg.vhd i2c_body.vhd \
		i2c_master_bit_ctrl.v \
		i2c_master_byte_ctrl.v \
		i2c_opencores_ctrl.vhd \
                i2c_master_defines.v

include $(OCPI_CDK_DIR)/include/hdl/hdl-lib.mk # we are a library of primitives
