% Generated on Fri Oct  5 08:46:18 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: biascapture}\\
        \hline
        \rowcolor{blue}
            Container & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base      & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 5721            & 4699       & 100.0            & \begin{tabular}{@{}l@{}}RAMB18E1: 2 \\ RAMB36E1: 21 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 5358            & 4507       & 100.0            & \begin{tabular}{@{}l@{}}RAMB18E1: 2 \\ RAMB36E1: 21 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & e3xx          & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 5675            & 4725       & 100.0            & \begin{tabular}{@{}l@{}}RAMB18E1: 2 \\ RAMB36E1: 21 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 10948           & 14309      & 125.534          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            base      & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 38238           & 24342      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 663506 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
