% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "testbias"}\\
        \hline
        \rowcolor{blue}
            Container & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 7280            & 5565       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 34\end{tabular} \\
            \hline
            base      & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 55767           & 33283      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 761972 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            base      & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 7643            & 5761       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 34\end{tabular} \\
            \hline
            base      & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 4802            & 6559       & 100.251          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            base      & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 14940           & 20737      & 124.285          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            use\_gp1  & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 4802            & 6559       & 100.251          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            use\_gp1  & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 7280            & 5565       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 34\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
