
# Put Makefile customizations for worker jm.rcc here:
SourceFiles = jmc.cilk
Path = /work/kulp/cilk/cilk/lib64
Libraries =  cilkutil cilkrts
LinkFiles = jmc.o


include $(OCPI_CDK_DIR)/include/worker.mk








