%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "dc_offset_filter"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions                        \\
		\hline
		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 350       & 326  & N/A        & \begin{tabular}{@{}c@{}}DSP18x18s=4\end{tabular}\\
		\hline
		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 350       & 363  & 165.245    & \begin{tabular}{@{}c@{}}DSP48E1s=2\end{tabular} \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 353       & 274  & 125.235    & \begin{tabular}{@{}c@{}}DSP48E1s=2\end{tabular} \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 350       & 364  & 167.403    & \begin{tabular}{@{}c@{}}DSP48E1s=2\end{tabular} \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
