% Generated on Fri Sep 28 16:14:09 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {3}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: capture\_v2}\\
        \hline
        \rowcolor{blue}
            Configuration & numDataWords & numRecords \\
            \hline
            0             & 1024         & 256 \\
            \hline
        \end{longtable}
\end{tiny}
