% Generated on Fri Oct  5 08:45:57 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: capture\_v2}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 412             & 678        & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 1 \\ RAMB36E1: 3\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 384             & 870        & 158.421          & \begin{tabular}{@{}l@{}}DSP48E1: 2 \\ RAMB36E1: 5\end{tabular} \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 415             & 813        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 65536\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
