% Generated on Fri Oct  5 08:46:00 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: flash}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool   & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado & 2017.1  & xc7z020clg400-3 & 23              & 13         & N/A              & N/A \\
            \hline
            0             & virtex6     & ISE    & 14.7    & 6vcx75tff484-2  & 1               & 1          & 1173.502         & N/A \\
            \hline
        \end{longtable}
\end{tiny}
