%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "flash"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool   & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		virtex6        & ISE    & 14.7    & 6vcx75tff484-2  & 1         & 1    & 1173.502   & N/A                     \\
		\hline
		zynq           & Vivado & 2017.1  & xc7z020clg400-3 & 23        & 13   & 562.746    & N/A                     \\
		\hline
		zynq\_ise      & ISE    & 14.7    & 7z010clg400-3   & 1         & 1    & 1505.344   & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
