% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_adc\_ts\_sub}\\
        \hline
        \rowcolor{blue}
            Configuration & SINGLE\_PORT\_p & LVDS\_p & DATA\_RATE\_CONFIG\_p & HALF\_DUPLEX\_p \\
            \hline
            0             & false           & true    & DDR                   & false \\
            \hline
            1             & true            & false   & DDR                   & false \\
            \hline
        \end{longtable}
\end{tiny}
