% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "ad9361\_adc\_ts\_sub"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool   & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq\_ise   & ISE    & 14.7    & 7z020clg484-1    & 155             & 161        & 468.165          & \begin{tabular}{@{}l@{}}BUFR: 1\end{tabular} \\
            \hline
            0             & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 155             & 161        & 437.445          & \begin{tabular}{@{}l@{}}BUFR: 1\end{tabular} \\
            \hline
            0             & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 175             & 89         & N/A              & \begin{tabular}{@{}l@{}}BUFR: 1\end{tabular} \\
            \hline
            1             & zynq\_ise   & ISE    & 14.7    & 7z020clg484-1    & 155             & 161        & 468.165          & N/A \\
            \hline
            1             & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 155             & 161        & 437.445          & N/A \\
            \hline
            1             & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 175             & 89         & N/A              & N/A \\
            \hline
        \end{longtable}
\end{tiny}
