% Generated on Fri Sep 28 16:14:06 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {11}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: cic\_int}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_endian & ocpi\_debug & ACC\_WIDTH & DOUT\_WIDTH & CHIPSCOPE\_p & DIN\_WIDTH & N & M & VIVADO\_ILA\_p & R \\
            \hline
            0             & little       & false       & 22         & 16          & false        & 16         & 3 & 1 & false          & 4 \\
            \hline
            1             & little       & false       & 25         & 16          & false        & 16         & 3 & 2 & false          & 4 \\
            \hline
            2             & little       & false       & 23         & 16          & false        & 16         & 3 & 1 & false          & 5 \\
            \hline
            3             & little       & false       & 26         & 16          & false        & 16         & 3 & 2 & false          & 5 \\
            \hline
            4             & little       & false       & 25         & 16          & false        & 16         & 3 & 1 & false          & 8 \\
            \hline
            5             & little       & false       & 28         & 16          & false        & 16         & 3 & 1 & false          & 16 \\
            \hline
            6             & little       & false       & 49         & 16          & false        & 16         & 3 & 1 & false          & 2048 \\
            \hline
            7             & little       & false       & 52         & 16          & false        & 16         & 3 & 2 & false          & 2048 \\
            \hline
            8             & little       & false       & 60         & 16          & false        & 16         & 4 & 1 & N/A            & 2048 \\
            \hline
            9             & little       & false       & 55         & 16          & false        & 16         & 3 & 1 & N/A            & 8191 \\
            \hline
            10            & little       & false       & 58         & 16          & false        & 16         & 3 & 2 & N/A            & 8191 \\
            \hline
            11            & little       & false       & 55         & 16          & false        & 16         & 3 & 1 & N/A            & 8192 \\
            \hline
            12            & little       & false       & 58         & 16          & false        & 16         & 3 & 2 & N/A            & 8192 \\
            \hline
        \end{longtable}
\end{tiny}
