% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {11}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: cic\_int}\\
        \hline
        \rowcolor{blue}
            Configuration & DOUT\_WIDTH & ocpi\_debug & M & R    & VIVADO\_ILA\_p & CHIPSCOPE\_p & ACC\_WIDTH & ocpi\_endian & N & DIN\_WIDTH \\
            \hline
            0             & 16          & false       & 1 & 4    & false          & false        & 22         & little       & 3 & 16 \\
            \hline
            1             & 16          & false       & 2 & 4    & false          & false        & 25         & little       & 3 & 16 \\
            \hline
            2             & 16          & false       & 1 & 5    & false          & false        & 23         & little       & 3 & 16 \\
            \hline
            3             & 16          & false       & 2 & 5    & false          & false        & 26         & little       & 3 & 16 \\
            \hline
            4             & 16          & false       & 1 & 8    & false          & false        & 25         & little       & 3 & 16 \\
            \hline
            5             & 16          & false       & 1 & 16   & false          & false        & 28         & little       & 3 & 16 \\
            \hline
            6             & 16          & false       & 1 & 2048 & false          & false        & 49         & little       & 3 & 16 \\
            \hline
            7             & 16          & false       & 2 & 2048 & false          & false        & 52         & little       & 3 & 16 \\
            \hline
            8             & 16          & false       & 1 & 2048 & N/A            & false        & 60         & little       & 4 & 16 \\
            \hline
            9             & 16          & false       & 1 & 8191 & N/A            & false        & 55         & little       & 3 & 16 \\
            \hline
            10            & 16          & false       & 2 & 8191 & N/A            & false        & 58         & little       & 3 & 16 \\
            \hline
            11            & 16          & false       & 1 & 8192 & N/A            & false        & 55         & little       & 3 & 16 \\
            \hline
            12            & 16          & false       & 2 & 8192 & N/A            & false        & 58         & little       & 3 & 16 \\
            \hline
        \end{longtable}
\end{tiny}
