% Generated on Fri Oct  5 08:45:55 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: cic\_int}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 582             & 453        & N/A              & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 545             & 540        & 329.707          & N/A \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 584             & 475        & N/A              & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 734             & 483        & N/A              & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 665             & 558        & 329.707          & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 736             & 499        & N/A              & N/A \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 597             & 458        & N/A              & N/A \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 553             & 550        & 329.707          & N/A \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 597             & 486        & N/A              & N/A \\
            \hline
            3             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 751             & 488        & N/A              & N/A \\
            \hline
            3             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 673             & 568        & 329.707          & N/A \\
            \hline
            3             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 751             & 510        & N/A              & N/A \\
            \hline
            4             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 621             & 485        & N/A              & N/A \\
            \hline
            4             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 565             & 562        & 329.707          & N/A \\
            \hline
            4             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 621             & 504        & N/A              & N/A \\
            \hline
            5             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 656             & 518        & N/A              & N/A \\
            \hline
            5             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 585             & 585        & 327.335          & N/A \\
            \hline
            5             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 658             & 531        & N/A              & N/A \\
            \hline
            6             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 915             & 731        & N/A              & N/A \\
            \hline
            6             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 725             & 748        & 305.46           & N/A \\
            \hline
            6             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 917             & 699        & N/A              & N/A \\
            \hline
            7             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1121            & 761        & N/A              & N/A \\
            \hline
            7             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 845             & 767        & 304.09           & N/A \\
            \hline
            7             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1123            & 725        & N/A              & N/A \\
            \hline
            8             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1408            & 1089       & N/A              & N/A \\
            \hline
            8             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 990             & 974        & 301.643          & N/A \\
            \hline
            8             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1410            & 1029       & N/A              & N/A \\
            \hline
            9             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 989             & 802        & N/A              & N/A \\
            \hline
            9             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 765             & 792        & 297.044          & N/A \\
            \hline
            9             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 991             & 748        & N/A              & N/A \\
            \hline
            10            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1207            & 832        & N/A              & N/A \\
            \hline
            10            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 885             & 810        & 297.044          & N/A \\
            \hline
            10            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1209            & 774        & N/A              & N/A \\
            \hline
            11            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 989             & 799        & N/A              & N/A \\
            \hline
            11            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 764             & 794        & 297.044          & N/A \\
            \hline
            11            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 991             & 751        & N/A              & N/A \\
            \hline
            12            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1207            & 828        & N/A              & N/A \\
            \hline
            12            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 885             & 821        & 301.296          & N/A \\
            \hline
            12            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1209            & 777        & N/A              & N/A \\
            \hline
        \end{longtable}
\end{tiny}
