%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "cic_int"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+DOUT_WIDTH=16+
	\item \verb+CHIPSCOPE_p=false+
	\item \verb+DIN_WIDTH=16+
	\item \verb+ACC_WIDTH=22+
	\item \verb+M=1+
	\item \verb+N=3+
	\item \verb+ocpi_endian=little+
	\item \verb+R=4+
	\item \verb+ocpi_debug=false+
	\item \verb+VIVADO_ILA_p=false+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 584       & 475  & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 545       & 540  & 329.707    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 582       & 453  & 203.417    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 545       & 542  & 353.357    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
%\textbf{Worker Build Configuration ``1'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=25+
%	\item \verb+M=2+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=4+
%	\item \verb+ocpi_debug=false+
%	\item \verb+VIVADO_ILA_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``1''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 736       & 499  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 665       & 558  & 329.707    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 734       & 483  & 202.963    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 665       & 560  & 353.357    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``2'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=23+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=5+
%	\item \verb+ocpi_debug=false+
%	\item \verb+VIVADO_ILA_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``2''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 597       & 486  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 553       & 550  & 329.707    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 597       & 458  & 182.916    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 553       & 551  & 353.357    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``3'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=26+
%	\item \verb+M=2+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=5+
%	\item \verb+ocpi_debug=false+
%	\item \verb+VIVADO_ILA_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``3''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 751       & 510  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 673       & 568  & 329.707    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 751       & 488  & 182.815    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 673       & 569  & 353.357    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``4'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=25+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=8+
%	\item \verb+ocpi_debug=false+
%	\item \verb+VIVADO_ILA_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``4''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 621       & 504  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 565       & 562  & 329.707    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 621       & 485  & 175.531    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 565       & 563  & 353.357    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``5'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=28+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=16+
%	\item \verb+ocpi_debug=false+
%	\item \verb+VIVADO_ILA_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``5''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 658       & 531  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 585       & 585  & 327.335    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 656       & 518  & 203.293    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 585       & 586  & 351.745    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``6'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=49+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=2048+
%	\item \verb+ocpi_debug=false+
%	\item \verb+VIVADO_ILA_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``6''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 917       & 699  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 725       & 748  & 305.460    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 915       & 731  & 193.386    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 725       & 743  & 324.886    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``7'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=52+
%	\item \verb+M=2+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=2048+
%	\item \verb+ocpi_debug=false+
%	\item \verb+VIVADO_ILA_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``7''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1123      & 725  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 845       & 767  & 304.090    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1121      & 761  & 193.125    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 845       & 761  & 324.886    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``8'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=60+
%	\item \verb+M=1+
%	\item \verb+N=4+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=2048+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``8''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs  & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1410      & 1,029 & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 990       & 974   & 301.643    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1408      & 1089  & 203.376    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 989       & 979   & 316.456    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``9'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=55+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=8191+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``9''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 991       & 748  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 765       & 792  & 297.044    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 989       & 802  & 203.252    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 765       & 792  & 311.139    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``10'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=58+
%	\item \verb+M=2+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=8191+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``10''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1209      & 774  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 885       & 810  & 297.044    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1207      & 832  & 203.128    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 885       & 810  & 311.139    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``11'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=55+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=8192+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``11''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 991       & 751  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 764       & 794  & 297.044    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 989       & 799  & 192.827    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 765       & 785  & 321.750    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``12'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+CHIPSCOPE_p=false+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=58+
%	\item \verb+M=2+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=8192+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``12''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1209      & 777  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 885       & 821  & 301.296    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1207      & 828  & 192.641    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 885       & 803  & 321.750    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
