% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "cic\_int"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 681             & 472        & N/A              & N/A \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 678             & 548        & N/A              & N/A \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 639             & 611        & 252.016          & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 639             & 612        & 224.227          & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 833             & 496        & N/A              & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 830             & 578        & N/A              & N/A \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 759             & 629        & 252.016          & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 759             & 630        & 224.569          & N/A \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 694             & 483        & N/A              & N/A \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 691             & 557        & N/A              & N/A \\
            \hline
            2             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 645             & 625        & 251.361          & N/A \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 645             & 626        & 238.607          & N/A \\
            \hline
            3             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 848             & 507        & N/A              & N/A \\
            \hline
            3             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 845             & 588        & N/A              & N/A \\
            \hline
            3             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 765             & 643        & 251.112          & N/A \\
            \hline
            3             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 765             & 644        & 238.607          & N/A \\
            \hline
            4             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 718             & 499        & N/A              & N/A \\
            \hline
            4             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 715             & 580        & N/A              & N/A \\
            \hline
            4             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 659             & 636        & 252.321          & N/A \\
            \hline
            4             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 659             & 637        & 238.607          & N/A \\
            \hline
            5             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 755             & 524        & N/A              & N/A \\
            \hline
            5             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 752             & 610        & N/A              & N/A \\
            \hline
            5             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 679             & 659        & 252.016          & N/A \\
            \hline
            5             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 679             & 660        & 238.265          & N/A \\
            \hline
            6             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1014            & 722        & N/A              & N/A \\
            \hline
            6             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1011            & 837        & N/A              & N/A \\
            \hline
            6             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 819             & 856        & 245.415          & N/A \\
            \hline
            6             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 819             & 857        & 231.015          & N/A \\
            \hline
            7             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1220            & 746        & N/A              & N/A \\
            \hline
            7             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1217            & 867        & N/A              & N/A \\
            \hline
            7             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 939             & 874        & 243.817          & N/A \\
            \hline
            7             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 939             & 875        & 229.598          & N/A \\
            \hline
            8             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1507            & 1042       & N/A              & N/A \\
            \hline
            8             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1504            & 1193       & N/A              & N/A \\
            \hline
            8             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1084            & 1083       & 244.378          & N/A \\
            \hline
            8             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1084            & 1084       & 230.468          & N/A \\
            \hline
            9             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1088            & 777        & N/A              & N/A \\
            \hline
            9             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1085            & 906        & N/A              & N/A \\
            \hline
            9             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 859             & 924        & 252.016          & N/A \\
            \hline
            9             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 859             & 927        & 238.607          & N/A \\
            \hline
            10            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1306            & 801        & N/A              & N/A \\
            \hline
            10            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1303            & 936        & N/A              & N/A \\
            \hline
            10            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 979             & 942        & 252.016          & N/A \\
            \hline
            10            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 979             & 945        & 237.511          & N/A \\
            \hline
            11            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1088            & 776        & N/A              & N/A \\
            \hline
            11            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1085            & 902        & N/A              & N/A \\
            \hline
            11            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 859             & 898        & 253.026          & N/A \\
            \hline
            11            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 859             & 901        & 238.607          & N/A \\
            \hline
            12            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1306            & 800        & N/A              & N/A \\
            \hline
            12            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1303            & 932        & N/A              & N/A \\
            \hline
            12            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 979             & 916        & 252.016          & N/A \\
            \hline
            12            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 979             & 919        & 237.511          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
