% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_data\_ts\_sub}\\
        \hline
        \rowcolor{blue}
            Configuration & RX\_Data\_Delay & LVDS\_p & TX\_Data\_Delay & DATA\_CLK\_Delay & SWAP\_PORTS\_p & SINGLE\_PORT\_p & FB\_CLK\_Delay & HALF\_DUPLEX\_p \\
            \hline
            0             & 0               & true    & 0               & 2                & false          & false           & 7              & false \\
            \hline
            1             & 0               & true    & 0               & 3                & false          & false           & 7              & false \\
            \hline
            2             & 0               & false   & 0               & 7                & false          & true            & 12             & false \\
            \hline
            3             & 0               & false   & 0               & 7                & true           & true            & 12             & false \\
            \hline
            4             & 0               & false   & 0               & 7                & false          & false           & 12             & false \\
            \hline
            5             & 0               & false   & 0               & 7                & true           & false           & 12             & false \\
            \hline
        \end{longtable}
\end{tiny}
