OCPI_DIR=../ocpi
Implementations = \
	adc.rcc \
	adc_unpack.rcc \
	bias.hdl \
	convert_s16_f32.rcc \
	copy.rcc \
	dac.rcc \
	delay.hdl \
	delay.rcc \
	framegate.hdl \
	framegate.rcc \
	morph_mean.rcc \
	psd.hdl \
	sma.hdl \
	split1x2.rcc \
	splitter2x2.hdl \
	splitter2x2.rcc \
	wbr.hdl \
	testmulti.rcc \
	testzc.rcc
HdlTargets=xc5vsx95t-2-ff1136 xc5vlx50t-ff1136-1
# xc6vlx240t-1-ff1156  xc5vlx330t-2-ff1738
RccTargets=$(HostTarget)
include $(OCPI_DIR)/include/lib.mk
