% Generated on Fri Sep 28 16:14:11 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_dac\_sub}\\
        \hline
        \rowcolor{blue}
            Configuration & DATA\_RATE\_CONFIG\_p & SINGLE\_PORT\_p & HALF\_DUPLEX\_p & LVDS\_p \\
            \hline
            0             & DDR                   & false           & false           & true \\
            \hline
            1             & DDR                   & true            & false           & false \\
            \hline
        \end{longtable}
\end{tiny}
