%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "ad9361_dac_sub"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+DATA_RATE_CONFIG_p=DDR+
	\item \verb+SINGLE_PORT_p=false+
	\item \verb+HALF_DUPLEX_p=false+
	\item \verb+LVDS_p=true+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool   & Version & Device           & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		virtex6        & ISE    & 14.7    & 6vlx240tff1156-1 & 99        & 105  & 632.511    & N/A                     \\
		\hline
		zynq           & Vivado & 2017.1  & xc7z020clg484-1  & 91        & 88   & 199.164    & N/A                     \\
		\hline
		zynq\_ise      & ISE    & 14.7    & 7z020clg484-1    & 99        & 105  & 704.225    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
