% Generated on Fri Oct  5 08:46:14 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: adapt}\\
        \hline
        \rowcolor{blue}
            Container & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base      & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 55723           & 32576      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 745590 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            base      & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 14848           & 20556      & 126.151          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            base      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 6955            & 5238       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & e3xx          & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 7272            & 5449       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 7318            & 5424       & 100.0            & \begin{tabular}{@{}l@{}}RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
