# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

Core=dram_v5_mig34
Top=v5_mig34
ExcludeTargets=
OnlyTargets=virtex5 isim xsim
SourceFiles=\
 ddr2_ctrl.v\
 ddr2_mem_if_top.v\
 ddr2_phy_calib.v\
 ddr2_phy_ctl_io.v\
 ddr2_phy_dm_iob.v\
 ddr2_phy_dq_iob.v\
 ddr2_phy_dqs_iob.v\
 ddr2_phy_init.v\
 ddr2_phy_io.v\
 ddr2_phy_top.v\
 ddr2_phy_write.v\
 ddr2_top.v\
 ddr2_usr_addr_fifo.v\
 ddr2_usr_rd.v\
 ddr2_usr_top.v\
 ddr2_usr_wr.v\
 ddr2_idelay_ctrl_eco20100514.v\
 ddr2_infrastructure_eco20100512.v\
 v5_mig34.v\
# end of files
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk
