% Generated on Fri Oct  5 08:47:50 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: mfsk2\_zp16\_fir\_real\_phase\_to\_amp\_cordic\_cic\_int}\\
        \hline
        \rowcolor{blue}
            Container                                               & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base                                                    & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 21500           & 28742      & 125.109          & \begin{tabular}{@{}l@{}}DSP48E1: 68 \\ BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            base                                                    & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 63515           & 40554      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 745590 \\ PLL: 1 \\ DSP18: 136 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            base                                                    & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 15126           & 11675      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 66 \\ RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base                                                    & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 14763           & 11472      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 66 \\ RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base                                                    & e3xx          & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 15080           & 11733      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 66 \\ RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605 & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 21500           & 28742      & 125.109          & \begin{tabular}{@{}l@{}}DSP48E1: 68 \\ BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 14763           & 11472      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 66 \\ RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_thruasm\_matchstiq\_z1                   & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 15126           & 11675      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 66 \\ RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_thruasm\_zipper\_hpc\_ml605              & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 21500           & 28742      & 125.109          & \begin{tabular}{@{}l@{}}DSP48E1: 68 \\ BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_thruasm\_zipper\_hsmc\_a\_alst4          & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 63515           & 40554      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 745590 \\ PLL: 1 \\ DSP18: 136 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_thruasm\_zipper\_hsmc\_b\_alst4          & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 63515           & 40554      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 745590 \\ PLL: 1 \\ DSP18: 136 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_thruasm\_zipper\_lpc\_ml605              & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 21500           & 28742      & 125.109          & \begin{tabular}{@{}l@{}}DSP48E1: 68 \\ BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_thruasm\_zipper\_lpc\_zed                & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 14763           & 11472      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 66 \\ RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
