% Generated on Mon Feb 25 10:09:54 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {2}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: fir\_complex\_sse}\\
        \hline
        \rowcolor{blue}
            Configuration & COEFF\_WIDTH\_p \\
            \hline
            0             & 16 \\
            \hline
            1             & 8 \\
            \hline
        \end{longtable}
\end{tiny}
