% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {3}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: fir\_complex\_sse\_ts}\\
        \hline
        \rowcolor{blue}
            Configuration & NUM\_TAPS\_p & COEFF\_WIDTH\_p \\
            \hline
            0             & 32           & 16 \\
            \hline
            1             & 32           & 8 \\
            \hline
            2             & 128          & 16 \\
            \hline
        \end{longtable}
\end{tiny}
