% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "fir\_complex\_sse\_ts"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 3275            & 2582       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 64\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 2416            & 2713       & 217.604          & \begin{tabular}{@{}l@{}}DSP48E1: 32\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 2416            & 2713       & 183.056          & \begin{tabular}{@{}l@{}}DSP48E1: 32\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 1584            & 1988       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 32\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 3147            & 2508       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 64\end{tabular} \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 2160            & 2678       & 217.817          & \begin{tabular}{@{}l@{}}DSP48E1: 32\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 2160            & 2678       & 187.864          & \begin{tabular}{@{}l@{}}DSP48E1: 32\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 1584            & 1919       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 32\end{tabular} \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & N/A             & 11821           & 9274       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 256\end{tabular} \\
            \hline
            2             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 12692           & 64424      & 146.69           & N/A \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 8564            & 9350       & 183.056          & \begin{tabular}{@{}l@{}}DSP48E1: 128\end{tabular} \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 8035            & 6674       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 128\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
