// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __hello_hh__
#define __hello_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_hello
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_hello
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_hello
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





#ifndef __Hello__
#define __Hello__

class Hello;
class _objref_Hello;
class _impl_Hello;

typedef _objref_Hello* Hello_ptr;
typedef Hello_ptr HelloRef;

class Hello_Helper {
public:
  typedef Hello_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_Hello, Hello_Helper> Hello_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_Hello,Hello_Helper > Hello_out;

#endif

// interface Hello
class Hello {
public:
  // Declarations for this interface type.
  typedef Hello_ptr _ptr_type;
  typedef Hello_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  
};

class _objref_Hello :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  void send(const char* mesg);

  inline _objref_Hello()  { _PR_setobj(0); }  // nil
  _objref_Hello(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_Hello();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_Hello(const _objref_Hello&);
  _objref_Hello& operator = (const _objref_Hello&);
  // not implemented

  friend class Hello;
};

class _pof_Hello : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_Hello() : _OMNI_NS(proxyObjectFactory)(Hello::_PD_repoId) {}
  virtual ~_pof_Hello();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_Hello :
  public virtual omniServant
{
public:
  virtual ~_impl_Hello();

  virtual void send(const char* mesg) = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};


_CORBA_GLOBAL_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_Hello;



class POA_Hello :
  public virtual _impl_Hello,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_Hello();

  inline ::Hello_ptr _this() {
    return (::Hello_ptr) _do_this(::Hello::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, Hello_ptr _s);
void operator<<=(::CORBA::Any& _a, Hello_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, Hello_ptr& _s);



inline void
Hello::_marshalObjRef(::Hello_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_hello
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_hello
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_hello
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_hello
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_hello
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_hello
#endif

#endif  // __hello_hh__

