% Generated on Fri Sep 28 16:14:11 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_spi}\\
        \hline
        \rowcolor{blue}
            Configuration & CP\_CLK\_FREQ\_HZ\_p & ocpi\_endian & ocpi\_debug & SPI\_CLK\_FREQ\_HZ\_p \\
            \hline
            0             & 100000000.0          & little       & false       & 6250000.0 \\
            \hline
            1             & 125000000.0          & little       & false       & 6250000.0 \\
            \hline
        \end{longtable}
\end{tiny}
