% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_spi}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_debug & CP\_CLK\_FREQ\_HZ\_p & ocpi\_endian & SPI\_CLK\_FREQ\_HZ\_p \\
            \hline
            0             & false       & 100000000.0          & little       & 6250000.0 \\
            \hline
            1             & false       & 125000000.0          & little       & 6250000.0 \\
            \hline
        \end{longtable}
\end{tiny}
