% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_data\_sub}\\
        \hline
        \rowcolor{blue}
            Configuration & LVDS\_p & HALF\_DUPLEX\_p & FB\_CLK\_Delay & RX\_Data\_Delay & SINGLE\_PORT\_p & TX\_Data\_Delay & SWAP\_PORTS\_p & DATA\_CLK\_Delay \\
            \hline
            0             & true    & false           & 7              & 0               & false           & 0               & false          & 2 \\
            \hline
            1             & true    & false           & 7              & 0               & false           & 0               & false          & 3 \\
            \hline
            2             & false   & false           & 12             & 0               & true            & 0               & false          & 7 \\
            \hline
            3             & false   & false           & 12             & 0               & true            & 0               & true           & 7 \\
            \hline
            4             & false   & false           & 12             & 0               & false           & 0               & false          & 7 \\
            \hline
            5             & false   & false           & 12             & 0               & false           & 0               & true           & 7 \\
            \hline
        \end{longtable}
\end{tiny}
