% Generated on Fri Sep 28 16:14:11 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_data\_sub}\\
        \hline
        \rowcolor{blue}
            Configuration & SWAP\_PORTS\_p & RX\_Data\_Delay & HALF\_DUPLEX\_p & DATA\_CLK\_Delay & SINGLE\_PORT\_p & FB\_CLK\_Delay & LVDS\_p & TX\_Data\_Delay \\
            \hline
            0             & false          & 0               & false           & 2                & false           & 7              & true    & 0 \\
            \hline
            1             & false          & 0               & false           & 3                & false           & 7              & true    & 0 \\
            \hline
            2             & false          & 0               & false           & 7                & true            & 12             & false   & 0 \\
            \hline
            3             & true           & 0               & false           & 7                & true            & 12             & false   & 0 \\
            \hline
            4             & false          & 0               & false           & 7                & false           & 12             & false   & 0 \\
            \hline
            5             & true           & 0               & false           & 7                & false           & 12             & false   & 0 \\
            \hline
        \end{longtable}
\end{tiny}
