%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "ad9361_data_sub"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+SINGLE_PORT_p=true+
	\item \verb+HALF_DUPLEX_p=true+
	\item \verb+SWAP_PORTS_p=false+
	\item \verb+LVDS_p=false+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 0         & 0    & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & N/A       & N/A  & N/A        & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 0         & 0    & 527.983    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & N/A       & N/A  & N/A        & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
%\textbf{Worker Build Configuration ``1'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+SINGLE_PORT_p=true+
%	\item \verb+HALF_DUPLEX_p=true+
%	\item \verb+SWAP_PORTS_p=true+
%	\item \verb+LVDS_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``1''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device                & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2       & 0         & 0    & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1      & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1       & 0         & 0    & 527.983    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1         & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``2'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+SINGLE_PORT_p=true+
%	\item \verb+HALF_DUPLEX_p=false+
%	\item \verb+SWAP_PORTS_p=false+
%	\item \verb+LVDS_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``2''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device                & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2       & 0         & 0    & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1      & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1       & 0         & 0    & 281.136    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1         & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``3'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+SINGLE_PORT_p=true+
%	\item \verb+HALF_DUPLEX_p=false+
%	\item \verb+SWAP_PORTS_p=true+
%	\item \verb+LVDS_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``3''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device                & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2       & 0         & 0    & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1      & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1       & 0         & 0    & 281.136    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1         & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``4'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+SINGLE_PORT_p=false+
%	\item \verb+HALF_DUPLEX_p=true+
%	\item \verb+SWAP_PORTS_p=false+
%	\item \verb+LVDS_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``4''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device                & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2       & 0         & 0    & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1      & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1       & 0         & 0    & 527.983    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1         & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``5'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+SINGLE_PORT_p=false+
%	\item \verb+HALF_DUPLEX_p=false+
%	\item \verb+SWAP_PORTS_p=false+
%	\item \verb+LVDS_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``5''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device                & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2       & 0         & 0    & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1      & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1       & 0         & 0    & 281.136    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1         & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``6'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+SINGLE_PORT_p=false+
%	\item \verb+HALF_DUPLEX_p=false+
%	\item \verb+SWAP_PORTS_p=true+
%	\item \verb+LVDS_p=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``6''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device                & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2       & 0         & 0    & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1      & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1       & 0         & 0    & 281.136    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1         & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``7'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+SINGLE_PORT_p=false+
%	\item \verb+LVDS_p=true+
%	\item \verb+HALF_DUPLEX_p=false+
%	\item \verb+SWAP_PORTS_p=false+
%	\item \verb+DATA_CLK_Delay=2+
%	\item \verb+RX_Data_Delay=0+
%	\item \verb+FB_CLK_Delay=7+
%	\item \verb+TX_Data_Delay=0+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``7''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device                & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2       & 0         & 0    & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1      & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1       & 0         & 0    & 351.494    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1         & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``8'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+SINGLE_PORT_p=false+
%	\item \verb+LVDS_p=true+
%	\item \verb+HALF_DUPLEX_p=false+
%	\item \verb+SWAP_PORTS_p=false+
%	\item \verb+DATA_CLK_Delay=3+
%	\item \verb+RX_Data_Delay=0+
%	\item \verb+FB_CLK_Delay=7+
%	\item \verb+TX_Data_Delay=0+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``8''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device                & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2       & 0         & 0    & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1      & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1       & 0         & 0    & 351.494    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1         & N/A       & N/A  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
