% Generated on Fri Oct  5 08:45:59 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: ad9361\_data\_sub}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool   & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 0               & 1          & N/A              & \begin{tabular}{@{}l@{}}BUFR: 1 \\ ODDR: 1\end{tabular} \\
            \hline
            0             & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 1               & 1          & N/A              & \begin{tabular}{@{}l@{}}ODDR: 1 \\ BUFR: 1\end{tabular} \\
            \hline
            1             & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 0               & 1          & N/A              & \begin{tabular}{@{}l@{}}BUFR: 1 \\ ODDR: 1\end{tabular} \\
            \hline
            1             & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 1               & 1          & N/A              & \begin{tabular}{@{}l@{}}ODDR: 1 \\ BUFR: 1\end{tabular} \\
            \hline
            2             & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 0               & 0          & N/A              & \begin{tabular}{@{}l@{}}BUFG: 1 \\ ODDR: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            2             & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 1               & N/A        & N/A              & \begin{tabular}{@{}l@{}}ODDR: 1 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            3             & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 0               & 0          & N/A              & \begin{tabular}{@{}l@{}}BUFG: 1 \\ ODDR: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            3             & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 1               & N/A        & N/A              & \begin{tabular}{@{}l@{}}ODDR: 1 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            4             & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 0               & 0          & N/A              & \begin{tabular}{@{}l@{}}BUFG: 1 \\ ODDR: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            4             & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 1               & N/A        & N/A              & \begin{tabular}{@{}l@{}}ODDR: 1 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            5             & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 0               & 0          & N/A              & \begin{tabular}{@{}l@{}}BUFG: 1 \\ ODDR: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            5             & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 1               & N/A        & N/A              & \begin{tabular}{@{}l@{}}ODDR: 1 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
