% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {4}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: zero\_pad}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_debug & DWIDTH\_p & ocpi\_endian \\
            \hline
            0             & false       & 8         & little \\
            \hline
            1             & false       & 16        & little \\
            \hline
            2             & false       & 32        & little \\
            \hline
            3             & false       & 64        & little \\
            \hline
        \end{longtable}
\end{tiny}
