% Generated on Fri Sep 28 16:14:09 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {4}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: zero\_pad}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_endian & ocpi\_debug & DWIDTH\_p \\
            \hline
            0             & little       & false       & 8 \\
            \hline
            1             & little       & false       & 16 \\
            \hline
            2             & little       & false       & 32 \\
            \hline
            3             & little       & false       & 64 \\
            \hline
        \end{longtable}
\end{tiny}
