% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "zero\_pad"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 225             & 262        & N/A              & N/A \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 223             & 289        & N/A              & N/A \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 221             & 368        & 199.601          & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 221             & 374        & 189.251          & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 260             & 282        & N/A              & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 258             & 310        & N/A              & N/A \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 256             & 401        & 196.58           & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 257             & 432        & 186.916          & N/A \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 331             & 298        & N/A              & N/A \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 329             & 377        & N/A              & N/A \\
            \hline
            2             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 327             & 458        & 195.465          & N/A \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 330             & 512        & 187.617          & N/A \\
            \hline
            3             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 474             & 319        & N/A              & N/A \\
            \hline
            3             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 472             & 474        & N/A              & N/A \\
            \hline
            3             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 468             & 594        & 219.78           & N/A \\
            \hline
            3             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 468             & 616        & 205.339          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
