OCPI_DIR=../../ocpi
SourceFiles_virtex6=$(wildcard *[vs]6*.v)
SourceFiles_virtex5=$(wildcard *[vs]5*.v)
SourceFiles=$(filter-out $(SourceFiles_virtex6) $(SourceFiles_virtex5),$(wildcard *.v))
include $(OCPI_DIR)/include/hdl/hdl-lib.mk
