%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "lime_spi"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 25        & 98   & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 22        & 106  & 603.336    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 23        & 69   & 312.695    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 22        & 106  & 772.380    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
