Top=pcie_hip_s4gx_gen2_x4_128
ExcludeTargets=
OnlyTargets=stratix4
SourceFiles=\
 pcie_hip_s4gx_gen2_x4_128.v\
 pcie_hip_s4gx_gen2_x4_128_core.v\
 pcie_hip_s4gx_gen2_x4_128_serdes.v\
 altpcie_hip_pipen1b.v\
 pciexp_dcram.v\
 altpcie_rs_serdes.v\
# end of files
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk
