% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {1}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: dc\_offset\_filter\_ts}\\
        \hline
        \rowcolor{blue}
            Configuration \\
            \hline
            0 \\
            \hline
        \end{longtable}
\end{tiny}
