% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "dc\_offset\_filter\_ts"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 465             & 371        & N/A              & \begin{tabular}{@{}l@{}}DSP18: 4\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 460             & 398        & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 2\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 457             & 535        & 167.403          & \begin{tabular}{@{}l@{}}DSP48E1: 2\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 457             & 535        & 165.245          & \begin{tabular}{@{}l@{}}DSP48E1: 2\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
