%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "sdp_send"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs  & Fmax (MHz) & Memory/Special Functions                         \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 1049      & 1907  & 298.232    & \begin{tabular}{@{}c@{}}RAMB36E1s=16\end{tabular}\\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 1049      & 1917  & 237.088    & \begin{tabular}{@{}c@{}}RAMB36E1s=16\end{tabular}\\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 1073      & 1423  & 184.196    & \begin{tabular}{@{}c@{}}RAMB36E1s=16\end{tabular}\\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 1046      & 1,362 & N/A        & N/A                                              \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
