HdlLibraries=ocpi fixed_float platform util axi
SourceFiles=sdp_pkg.vhd sdp_axi_pkg.vhd sdp_body.vhd unoc2sdp.vhd sdp_sim.vhd  sdp_term.vhd \
            sdp2axi_rd.vhd sdp2axi_wd.vhd sdp2axi.vhd sdp2axi_rd.vhd
include $(OCPI_CDK_DIR)/include/hdl/hdl-lib.mk
