% Generated on Fri Sep 28 16:13:48 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: wsi\_width\_adapter}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_endian & width\_out & width\_in & ocpi\_debug \\
            \hline
            0             & little       & 16         & 8         & false \\
            \hline
            1             & little       & 32         & 8         & false \\
            \hline
            2             & little       & 64         & 8         & false \\
            \hline
            3             & little       & 128        & 8         & false \\
            \hline
            4             & little       & 8          & 16        & false \\
            \hline
            5             & little       & 32         & 16        & false \\
            \hline
            6             & little       & 64         & 16        & false \\
            \hline
            7             & little       & 128        & 16        & false \\
            \hline
            8             & little       & 8          & 32        & false \\
            \hline
            9             & little       & 16         & 32        & false \\
            \hline
            10            & little       & 64         & 32        & false \\
            \hline
            11            & little       & 128        & 32        & false \\
            \hline
            12            & little       & 8          & 64        & false \\
            \hline
            13            & little       & 16         & 64        & false \\
            \hline
            14            & little       & 32         & 64        & false \\
            \hline
            15            & little       & 128        & 64        & false \\
            \hline
            16            & little       & 8          & 128       & false \\
            \hline
            17            & little       & 16         & 128       & false \\
            \hline
            18            & little       & 32         & 128       & false \\
            \hline
            19            & little       & 64         & 128       & false \\
            \hline
            20            & little       & 32         & 96        & false \\
            \hline
            21            & little       & 96         & 32        & false \\
            \hline
        \end{longtable}
\end{tiny}
