% Generated on Tue Apr 30 11:23:58 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: wsi\_width\_adapter}\\
        \hline
        \rowcolor{blue}
            Configuration & width\_out & width\_in & ocpi\_debug & ocpi\_endian \\
            \hline
            0             & 16         & 8         & false       & little \\
            \hline
            1             & 32         & 8         & false       & little \\
            \hline
            2             & 64         & 8         & false       & little \\
            \hline
            3             & 128        & 8         & false       & little \\
            \hline
            4             & 8          & 16        & false       & little \\
            \hline
            5             & 32         & 16        & false       & little \\
            \hline
            6             & 64         & 16        & false       & little \\
            \hline
            7             & 128        & 16        & false       & little \\
            \hline
            8             & 8          & 32        & false       & little \\
            \hline
            9             & 16         & 32        & false       & little \\
            \hline
            10            & 64         & 32        & false       & little \\
            \hline
            11            & 128        & 32        & false       & little \\
            \hline
            12            & 8          & 64        & false       & little \\
            \hline
            13            & 16         & 64        & false       & little \\
            \hline
            14            & 32         & 64        & false       & little \\
            \hline
            15            & 128        & 64        & false       & little \\
            \hline
            16            & 8          & 128       & false       & little \\
            \hline
            17            & 16         & 128       & false       & little \\
            \hline
            18            & 32         & 128       & false       & little \\
            \hline
            19            & 64         & 128       & false       & little \\
            \hline
            20            & 32         & 96        & false       & little \\
            \hline
            21            & 96         & 32        & false       & little \\
            \hline
        \end{longtable}
\end{tiny}
