%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "wsi_width_adapter"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+width_out=16+
	\item \verb+ocpi_debug=false+
	\item \verb+width_in=8+
	\item \verb+ocpi_endian=little+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 83        & 211  & 625.005    & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 84        & 185  & 403.080    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 86        & 78   & 342.114    & N/A                     \\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 84        & 92   & N/A        & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
%\textbf{Worker Build Configuration ``1'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=32+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=8+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``1''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 102       & 236  & 596.061    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 104       & 228  & 392.303    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 105       & 93   & 313.972    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 103       & 142  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``2'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=64+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=8+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``2''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 141       & 305  & 477.938    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 141       & 304  & 382.243    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 142       & 128  & 313.185    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 140       & 193  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``3'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=128+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=8+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``3''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 212       & 504  & 578.206    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 216       & 494  & 395.867    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 215       & 190  & 308.642    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 213       & 292  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``4'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=8+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=16+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``4''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 104       & 212  & 668.105    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 104       & 212  & 521.530    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 77   & 384.763    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 102       & 92   & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``5'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=32+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=16+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``5''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 120       & 298  & 615.789    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 121       & 262  & 403.055    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 122       & 99   & 298.329    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 120       & 123  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``6'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=64+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=16+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``6''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 156       & 381  & 589.992    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 158       & 340  & 394.011    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 159       & 158  & 298.329    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 157       & 195  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``7'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=128+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=16+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``7''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 231       & 483  & 481.748    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 231       & 483  & 381.730    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 232       & 176  & 298.329    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 230       & 287  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``8'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=8+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=32+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``8''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 157       & 318  & 542.299    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 157       & 272  & 428.816    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 156       & 115  & 334.001    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 156       & 130  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``9'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=16+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=32+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``9''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 156       & 319  & 665.651    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 156       & 319  & 519.714    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 155       & 118  & 338.295    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 155       & 125  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``10'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=64+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=32+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``10''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 193       & 464  & 601.707    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 193       & 409  & 393.546    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 194       & 137  & 306.560    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 192       & 174  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``11'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=128+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=32+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``11''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 265       & 574  & 576.333    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 266       & 566  & 384.165    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 267       & 188  & 305.064    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 265       & 262  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``12'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=8+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=64+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``12''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 264       & 426  & 533.618    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 264       & 426  & 418.148    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 262       & 201  & 298.507    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 262       & 174  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``13'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=16+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=64+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``13''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 261       & 592  & 634.498    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 262       & 503  & 428.816    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 261       & 156  & 297.974    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 261       & 185  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``14'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=32+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=64+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``14''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 262       & 595  & 660.797    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 262       & 262  & 431.016    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 261       & 166  & 364.564    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 261       & 185  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``15'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=128+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=64+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``15''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 337       & 715  & 584.109    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 337       & 706  & 378.630    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 338       & 217  & 296.296    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 336       & 373  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``16'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=8+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=128+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``16''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 472       & 748  & 454.504    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 472       & 288  & 361.330    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 472       & 328  & 95.265     & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 472       & 444  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``17'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=16+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=128+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``17''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 472       & 753  & 509.217    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 472       & 753  & 400.200    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 471       & 280  & 221.976    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 471       & 285  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``18'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=32+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=128+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``18''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 474       & 896  & 542.299    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 474       & 896  & 428.816    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 471       & 262  & 332.116    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 471       & 296  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``19'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=64+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=128+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``19''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 474       & 440  & 545.197    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 474       & 440  & 431.016    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 473       & 287  & 321.750    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 473       & 455  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``20'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=32+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=96+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``20''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 370       & 844  & 625.365    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 369       & 719  & 428.816    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 367       & 286  & 332.336    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 367       & 227  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``21'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+width_out=96+
%	\item \verb+ocpi_debug=false+
%	\item \verb+width_in=32+
%	\item \verb+ocpi_endian=little+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``21''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 229       & 496  & 583.100    & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 231       & 488  & 387.582    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 231       & 163  & 305.437    & N/A                     \\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 229       & 224  & N/A        & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
