% Generated on Fri Oct  5 08:45:37 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: wsi\_width\_adapter}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 86              & 78         & N/A              & N/A \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 84              & 92         & N/A              & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 84              & 185        & 403.08           & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 105             & 93         & N/A              & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 103             & 142        & N/A              & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 104             & 228        & 392.303          & N/A \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 142             & 128        & N/A              & N/A \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & N/A             & 140             & 193        & N/A              & N/A \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 141             & 304        & 382.243          & N/A \\
            \hline
            3             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 215             & 190        & N/A              & N/A \\
            \hline
            3             & stratix4    & Quartus & 17.1.0  & N/A             & 213             & 292        & N/A              & N/A \\
            \hline
            3             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 216             & 494        & 395.867          & N/A \\
            \hline
            4             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 77         & N/A              & N/A \\
            \hline
            4             & stratix4    & Quartus & 17.1.0  & N/A             & 102             & 92         & N/A              & N/A \\
            \hline
            4             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 104             & 212        & 521.53           & N/A \\
            \hline
            5             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 122             & 99         & N/A              & N/A \\
            \hline
            5             & stratix4    & Quartus & 17.1.0  & N/A             & 120             & 123        & N/A              & N/A \\
            \hline
            5             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 121             & 262        & 403.055          & N/A \\
            \hline
            6             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 159             & 158        & N/A              & N/A \\
            \hline
            6             & stratix4    & Quartus & 17.1.0  & N/A             & 157             & 195        & N/A              & N/A \\
            \hline
            6             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 158             & 340        & 394.011          & N/A \\
            \hline
            7             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 232             & 176        & N/A              & N/A \\
            \hline
            7             & stratix4    & Quartus & 17.1.0  & N/A             & 230             & 287        & N/A              & N/A \\
            \hline
            7             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 231             & 483        & 381.73           & N/A \\
            \hline
            8             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 156             & 115        & N/A              & N/A \\
            \hline
            8             & stratix4    & Quartus & 17.1.0  & N/A             & 156             & 130        & N/A              & N/A \\
            \hline
            8             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 157             & 272        & 428.816          & N/A \\
            \hline
            9             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 155             & 118        & N/A              & N/A \\
            \hline
            9             & stratix4    & Quartus & 17.1.0  & N/A             & 155             & 125        & N/A              & N/A \\
            \hline
            9             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 156             & 319        & 519.714          & N/A \\
            \hline
            10            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 194             & 137        & N/A              & N/A \\
            \hline
            10            & stratix4    & Quartus & 17.1.0  & N/A             & 192             & 174        & N/A              & N/A \\
            \hline
            10            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 193             & 409        & 393.546          & N/A \\
            \hline
            11            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 267             & 188        & N/A              & N/A \\
            \hline
            11            & stratix4    & Quartus & 17.1.0  & N/A             & 265             & 262        & N/A              & N/A \\
            \hline
            11            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 266             & 566        & 384.165          & N/A \\
            \hline
            12            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 262             & 201        & N/A              & N/A \\
            \hline
            12            & stratix4    & Quartus & 17.1.0  & N/A             & 262             & 174        & N/A              & N/A \\
            \hline
            12            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 264             & 426        & 418.148          & N/A \\
            \hline
            13            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 261             & 156        & N/A              & N/A \\
            \hline
            13            & stratix4    & Quartus & 17.1.0  & N/A             & 261             & 185        & N/A              & N/A \\
            \hline
            13            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 262             & 503        & 428.816          & N/A \\
            \hline
            14            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 261             & 166        & N/A              & N/A \\
            \hline
            14            & stratix4    & Quartus & 17.1.0  & N/A             & 261             & 185        & N/A              & N/A \\
            \hline
            14            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 262             & 262        & 431.016          & N/A \\
            \hline
            15            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 338             & 217        & N/A              & N/A \\
            \hline
            15            & stratix4    & Quartus & 17.1.0  & N/A             & 336             & 373        & N/A              & N/A \\
            \hline
            15            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 337             & 706        & 378.63           & N/A \\
            \hline
            16            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 472             & 328        & N/A              & N/A \\
            \hline
            16            & stratix4    & Quartus & 17.1.0  & N/A             & 472             & 444        & N/A              & N/A \\
            \hline
            16            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 472             & 288        & 361.33           & N/A \\
            \hline
            17            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 471             & 280        & N/A              & N/A \\
            \hline
            17            & stratix4    & Quartus & 17.1.0  & N/A             & 471             & 285        & N/A              & N/A \\
            \hline
            17            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 472             & 753        & 400.2            & N/A \\
            \hline
            18            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 471             & 262        & N/A              & N/A \\
            \hline
            18            & stratix4    & Quartus & 17.1.0  & N/A             & 471             & 296        & N/A              & N/A \\
            \hline
            18            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 474             & 896        & 428.816          & N/A \\
            \hline
            19            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 473             & 287        & N/A              & N/A \\
            \hline
            19            & stratix4    & Quartus & 17.1.0  & N/A             & 473             & 455        & N/A              & N/A \\
            \hline
            19            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 474             & 440        & 431.016          & N/A \\
            \hline
            20            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 367             & 286        & N/A              & N/A \\
            \hline
            20            & stratix4    & Quartus & 17.1.0  & N/A             & 367             & 227        & N/A              & N/A \\
            \hline
            20            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 369             & 719        & 428.816          & N/A \\
            \hline
            21            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 231             & 163        & N/A              & N/A \\
            \hline
            21            & stratix4    & Quartus & 17.1.0  & N/A             & 229             & 224        & N/A              & N/A \\
            \hline
            21            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 231             & 488        & 387.582          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
