% Generated on Tue Apr 30 11:23:58 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "wsi\_width\_adapter"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 137             & 219        & 280.434          & N/A \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 140             & 176        & N/A              & N/A \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 140             & 134        & N/A              & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 137             & 219        & 222.789          & N/A \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 155             & 261        & 311.808          & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 158             & 190        & N/A              & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 158             & 162        & N/A              & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 155             & 261        & 247.485          & N/A \\
            \hline
            2             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 192             & 307        & 344.66           & N/A \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 194             & 207        & N/A              & N/A \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & N/A             & 194             & 211        & N/A              & N/A \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 191             & 307        & 272.65           & N/A \\
            \hline
            3             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 266             & 395        & 304.321          & N/A \\
            \hline
            3             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 266             & 274        & N/A              & N/A \\
            \hline
            3             & stratix4    & Quartus & 17.1.0  & N/A             & 266             & 307        & N/A              & N/A \\
            \hline
            3             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 266             & 395        & 242.213          & N/A \\
            \hline
            4             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 175             & 278        & 320.39           & N/A \\
            \hline
            4             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 175             & 204        & N/A              & N/A \\
            \hline
            4             & stratix4    & Quartus & 17.1.0  & N/A             & 177             & 140        & N/A              & N/A \\
            \hline
            4             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 177             & 342        & 274.755          & N/A \\
            \hline
            5             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 192             & 314        & 310.578          & N/A \\
            \hline
            5             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 193             & 208        & N/A              & N/A \\
            \hline
            5             & stratix4    & Quartus & 17.1.0  & N/A             & 193             & 155        & N/A              & N/A \\
            \hline
            5             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 192             & 314        & 245.104          & N/A \\
            \hline
            6             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 228             & 350        & 310.145          & N/A \\
            \hline
            6             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 229             & 238        & N/A              & N/A \\
            \hline
            6             & stratix4    & Quartus & 17.1.0  & N/A             & 229             & 203        & N/A              & N/A \\
            \hline
            6             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 228             & 350        & 246.205          & N/A \\
            \hline
            7             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 301             & 427        & 303.601          & N/A \\
            \hline
            7             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 301             & 275        & N/A              & N/A \\
            \hline
            7             & stratix4    & Quartus & 17.1.0  & N/A             & 301             & 282        & N/A              & N/A \\
            \hline
            7             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 301             & 427        & 240.275          & N/A \\
            \hline
            8             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 267             & 431        & 346.062          & N/A \\
            \hline
            8             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 265             & 266        & N/A              & N/A \\
            \hline
            8             & stratix4    & Quartus & 17.1.0  & N/A             & 267             & 158        & N/A              & N/A \\
            \hline
            8             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 268             & 432        & 274.175          & N/A \\
            \hline
            9             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 264             & 414        & 357.015          & N/A \\
            \hline
            9             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 263             & 263        & N/A              & N/A \\
            \hline
            9             & stratix4    & Quartus & 17.1.0  & N/A             & 265             & 156        & N/A              & N/A \\
            \hline
            9             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 264             & 414        & 282.211          & N/A \\
            \hline
            10            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 297             & 470        & 333.194          & N/A \\
            \hline
            10            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 300             & 276        & N/A              & N/A \\
            \hline
            10            & stratix4    & Quartus & 17.1.0  & N/A             & 300             & 206        & N/A              & N/A \\
            \hline
            10            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 298             & 470        & 265.592          & N/A \\
            \hline
            11            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 369             & 490        & 296.62           & N/A \\
            \hline
            11            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 372             & 335        & N/A              & N/A \\
            \hline
            11            & stratix4    & Quartus & 17.1.0  & N/A             & 372             & 288        & N/A              & N/A \\
            \hline
            11            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 370             & 490        & 238.013          & N/A \\
            \hline
            12            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 444             & 529        & 307.915          & N/A \\
            \hline
            12            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 443             & 393        & N/A              & N/A \\
            \hline
            12            & stratix4    & Quartus & 17.1.0  & N/A             & 445             & 170        & N/A              & N/A \\
            \hline
            12            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 445             & 532        & 242.431          & N/A \\
            \hline
            13            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 441             & 538        & 310.965          & N/A \\
            \hline
            13            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 441             & 387        & N/A              & N/A \\
            \hline
            13            & stratix4    & Quartus & 17.1.0  & N/A             & 443             & 176        & N/A              & N/A \\
            \hline
            13            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 444             & 541        & 246.224          & N/A \\
            \hline
            14            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 442             & 520        & 318.107          & N/A \\
            \hline
            14            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 440             & 391        & N/A              & N/A \\
            \hline
            14            & stratix4    & Quartus & 17.1.0  & N/A             & 442             & 178        & N/A              & N/A \\
            \hline
            14            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 440             & 520        & 251.017          & N/A \\
            \hline
            15            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 514             & 548        & 282.247          & N/A \\
            \hline
            15            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 515             & 433        & N/A              & N/A \\
            \hline
            15            & stratix4    & Quartus & 17.1.0  & N/A             & 515             & 288        & N/A              & N/A \\
            \hline
            15            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 515             & 553        & 223.754          & N/A \\
            \hline
            16            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 801             & 706        & 309.635          & N/A \\
            \hline
            16            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 797             & 684        & N/A              & N/A \\
            \hline
            16            & stratix4    & Quartus & 17.1.0  & N/A             & 799             & 217        & N/A              & N/A \\
            \hline
            16            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 801             & 706        & 243.845          & N/A \\
            \hline
            17            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 799             & 893        & 318.903          & N/A \\
            \hline
            17            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 795             & 651        & N/A              & N/A \\
            \hline
            17            & stratix4    & Quartus & 17.1.0  & N/A             & 797             & 219        & N/A              & N/A \\
            \hline
            17            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 801             & 893        & 252.36           & N/A \\
            \hline
            18            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 797             & 859        & 310.54           & N/A \\
            \hline
            18            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 794             & 643        & N/A              & N/A \\
            \hline
            18            & stratix4    & Quartus & 17.1.0  & N/A             & 796             & 219        & N/A              & N/A \\
            \hline
            18            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 797             & 705        & 243.998          & N/A \\
            \hline
            19            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 796             & 853        & 323.29           & N/A \\
            \hline
            19            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 795             & 652        & N/A              & N/A \\
            \hline
            19            & stratix4    & Quartus & 17.1.0  & N/A             & 797             & 218        & N/A              & N/A \\
            \hline
            19            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 798             & 853        & 256.479          & N/A \\
            \hline
            20            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 620             & 715        & 326.8            & N/A \\
            \hline
            20            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 618             & 530        & N/A              & N/A \\
            \hline
            20            & stratix4    & Quartus & 17.1.0  & N/A             & 620             & 188        & N/A              & N/A \\
            \hline
            20            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 621             & 715        & 259.714          & N/A \\
            \hline
            21            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 334             & 510        & 333.678          & N/A \\
            \hline
            21            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 337             & 297        & N/A              & N/A \\
            \hline
            21            & stratix4    & Quartus & 17.1.0  & N/A             & 337             & 247        & N/A              & N/A \\
            \hline
            21            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 335             & 510        & 265.84           & N/A \\
            \hline
        \end{longtable}
\end{tiny}
