% Generated on Fri Oct  5 08:46:09 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: ad9361\_1r1t\_test\_asm}\\
        \hline
        \rowcolor{blue}
            Container                                                      & OCPI Platform & OCPI Target & Tool   & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_txsrc\_fmcomms\_2\_3\_lpc\_LVDS\_ml605 & ml605         & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 11216           & 21764      & 125.345          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_txsrc\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed           & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 6208            & 12750      & 350.14           & \begin{tabular}{@{}l@{}}RAMB18E1: 2 \\ BUFR: 3 \\ RAMB36E1: 18 \\ BUFG: 1 \\ ODDR: 8 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
