% Generated on Fri Sep 28 16:14:03 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {6}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: fir\_real\_sse}\\
        \hline
        \rowcolor{blue}
            Configuration & DATA\_WIDTH\_p & NUM\_TAPS\_p & ocpi\_endian & ocpi\_debug & COEFF\_WIDTH\_p \\
            \hline
            0             & 16             & 64           & little       & false       & 16 \\
            \hline
            1             & 16             & 128          & little       & false       & 16 \\
            \hline
        \end{longtable}
\end{tiny}
