% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "fir\_real\_sse"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 6512            & 5162       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 128\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 5403            & 3753       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 64\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 4378            & 5222       & 159.693          & \begin{tabular}{@{}l@{}}DSP48E1: 64\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 4378            & 5223       & 156.495          & \begin{tabular}{@{}l@{}}DSP48E1: 64\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 12721           & 10024      & N/A              & \begin{tabular}{@{}l@{}}DSP18: 256\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 9534            & 7367       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 128\end{tabular} \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 8475            & 9982       & 159.693          & \begin{tabular}{@{}l@{}}DSP48E1: 128\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 8475            & 9983       & 156.495          & \begin{tabular}{@{}l@{}}DSP48E1: 128\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
