# List of tested platforms
#OnlyPlatforms=zed
#OpenCores I2C Byte Controller Source Files
SourceFiles=	i2c_master_byte_ctrl.v \
		i2c_master_bit_ctrl.v 
Param_clkin_present=1
Param_clkin_freq=30.72e6
Param_outputs_present=1,0,1,1,1,1,0,0

include $(OCPI_CDK_DIR)/include/worker.mk
