# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

# Put Makefile customizations for worker multirate_counter.hdl here:
#SourceFiles=./clk_div.vhd \
#	./counter.vhd \
#	./fifo_32w_16d_63in_125out.vhd \
#	./user_pkg.vhd

#Libraries=~/ocpi_projects/pci_benchmark/hdl/prims
#Libraries=/opt/Xilinx/14.4/ISE_DS/ISE/vhdl/xst/lin64/xilinxcorelib

#Cores= ~/ocpi_projects/pci_benchmark/hdl/prims/fifo_32w_16d_63in_125out


include $(OCPI_CDK_DIR)/include/worker.mk
