% Generated on Fri Oct  5 08:48:09 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: tb\_bias\_v2}\\
        \hline
        \rowcolor{blue}
            Container & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base      & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 6614            & 6707       & 127.959          & \begin{tabular}{@{}l@{}}DSP48E1: 2 \\ BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            base      & e3xx          & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 4097            & 3563       & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 1 \\ RAMB36E1: 5 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 4143            & 3541       & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 1 \\ RAMB36E1: 5 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 3780            & 3361       & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 1 \\ RAMB36E1: 5 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 19777           & 12714      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 203492 \\ PLL: 1 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            ml6\_fl   & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 6614            & 6707       & 127.959          & \begin{tabular}{@{}l@{}}DSP48E1: 2 \\ BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
