% Generated on Tue Apr 30 11:23:58 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {2}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: wsi\_adapt\_to\_zero}\\
        \hline
        \rowcolor{blue}
            Configuration & width \\
            \hline
            0             & 32 \\
            \hline
        \end{longtable}
\end{tiny}
