% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "data\_src\_to\_dac"}\\
        \hline
        \rowcolor{blue}
            Container                                             & OCPI Platform & OCPI Target & Tool   & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_fmcomms\_2\_3\_lpc\_LVDS\_ml605 & ml605         & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 5623            & 6117       & 125.502          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed\_ise      & zynq\_ise   & ISE    & 14.7    & 7z020clg484-1    & 2662            & 3548       & N/A              & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed           & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 2726            & 2820       & 245.761          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 2 \\ ODDR: 8 \\ BUFR: 2 \\ RAMB18E1: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_matchstiq\_z1                   & matchstiq\_z1 & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 4375            & 4604       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 3 \\ BUFG: 3 \\ RAMB36E1: 2 \\ RAMB18E1: 3\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
