% Generated on Fri Oct  5 08:46:32 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: data\_src\_to\_dac}\\
        \hline
        \rowcolor{blue}
            Container                                             & OCPI Platform & OCPI Target & Tool   & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_fmcomms\_2\_3\_lpc\_LVDS\_ml605 & ml605         & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 5555            & 5976       & 125.094          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed           & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 2677            & 2690       & 245.761          & \begin{tabular}{@{}l@{}}RAMB18E1: 1 \\ BUFR: 2 \\ RAMB36E1: 2 \\ BUFG: 1 \\ ODDR: 8 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_matchstiq\_z1                   & matchstiq\_z1 & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 4160            & 4315       & 100.0            & \begin{tabular}{@{}l@{}}RAMB18E1: 3 \\ RAMB36E1: 2 \\ BUFG: 3 \\ BUFGCTRL: 3\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
