% Generated on Fri Oct  5 08:45:58 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: wsi\_16\_to\_32}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 68              & 62         & N/A              & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 69              & 193        & 494.698          & N/A \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 68              & 85         & N/A              & N/A \\
            \hline
        \end{longtable}
\end{tiny}
