% Generated on Fri Oct  5 08:47:05 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: dc\_offset\_iq\_imbalance\_mixer\_cic\_dec\_rp\_cordic\_fir\_real}\\
        \hline
        \rowcolor{blue}
            Container                                               & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_hpc\_LVDS\_ml605 & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 19483           & 25723      & 123.716          & \begin{tabular}{@{}l@{}}DSP48E1: 85 \\ BUFG: 7 \\ BUFGCTRL: 7\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605 & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 19483           & 25723      & 123.716          & \begin{tabular}{@{}l@{}}DSP48E1: 85 \\ BUFG: 7 \\ BUFGCTRL: 7\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 15415           & 14669      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 82 \\ RAMB36E1: 21 \\ BUFG: 2 \\ BUFGCTRL: 2\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_matchstiq\_z1                   & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 16470           & 15764      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 82 \\ RAMB18E1: 2 \\ RAMB36E1: 21 \\ BUFG: 2 \\ BUFGCTRL: 2\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_hpc\_ml605              & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 19483           & 25723      & 123.716          & \begin{tabular}{@{}l@{}}DSP48E1: 85 \\ BUFG: 7 \\ BUFGCTRL: 7\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_hsmc\_a\_alst4          & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 47758           & 34810      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 498918 \\ PLL: 1 \\ DSP18: 166 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_hsmc\_b\_alst4          & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 47758           & 34810      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 498918 \\ PLL: 1 \\ DSP18: 166 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_lpc\_ml605              & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 19483           & 25723      & 123.716          & \begin{tabular}{@{}l@{}}DSP48E1: 85 \\ BUFG: 7 \\ BUFGCTRL: 7\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_zipper\_lpc\_zed                & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 15415           & 14669      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 82 \\ RAMB36E1: 21 \\ BUFG: 2 \\ BUFGCTRL: 2\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
