
# #####
#
#  Copyright (c) Mercury Federal Systems, Inc., Arlington VA., 2009-2010
#
#    Mercury Federal Systems, Incorporated
#    1901 South Bell Street
#    Suite 402
#    Arlington, Virginia 22202
#    United States of America
#    Telephone 703-413-0781
#    FAX 703-413-0784
#
#  This file is part of OpenCPI (www.opencpi.org).
#     ____                   __________   ____
#    / __ \____  ___  ____  / ____/ __ \ /  _/ ____  _________ _
#   / / / / __ \/ _ \/ __ \/ /   / /_/ / / /  / __ \/ ___/ __ `/
#  / /_/ / /_/ /  __/ / / / /___/ ____/_/ / _/ /_/ / /  / /_/ /
#  \____/ .___/\___/_/ /_/\____/_/    /___/(_)____/_/   \__, /
#      /_/                                             /____/
#
#  OpenCPI is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  OpenCPI is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################### #

# This core was generated for one target
Top=v5_mig34
OnlyTargets=xc5vsx95t
Imports= \
  $(OCPI_HDL_IMPORTS_DIR)/coregen/dram_v5_mig34/mig_v3_4/user_design/rtl/*.v \
  $(OCPI_HDL_IMPORTS_DIR)/coregen/dram_v5_mig34/ddr2_idelay_ctrl_eco20100514.v \
  $(OCPI_HDL_IMPORTS_DIR)/coregen/dram_v5_mig34/ddr2_infrastructure_eco20100512.v \
  $(OCPI_HDL_IMPORTS_DIR)/libsrc/hdl/ocpi/v5_mig34.v
# Remove files that we have patched with other names
ExcludeImports=ddr2_chipscope.v ddr2_idelay_ctrl.v ddr2_infrastructure.v mig_v3_4.v
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk # We are a (compiled) core






