
/*
 *  Copyright (c) Mercury Federal Systems, Inc., Arlington VA., 2009-2010
 *
 *    Mercury Federal Systems, Incorporated
 *    1901 South Bell Street
 *    Suite 402
 *    Arlington, Virginia 22202
 *    United States of America
 *    Telephone 703-413-0781
 *    FAX 703-413-0784
 *
 *  This file is part of OpenCPI (www.opencpi.org).
 *     ____                   __________   ____
 *    / __ \____  ___  ____  / ____/ __ \ /  _/ ____  _________ _
 *   / / / / __ \/ _ \/ __ \/ /   / /_/ / / /  / __ \/ ___/ __ `/
 *  / /_/ / /_/ /  __/ / / / /___/ ____/_/ / _/ /_/ / /  / /_/ /
 *  \____/ .___/\___/_/ /_/\____/_/    /___/(_)____/_/   \__, /
 *      /_/                                             /____/
 *
 *  OpenCPI is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  OpenCPI is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _LIFECYCLE_IDL
#define _LIFECYCLE_IDL

#include "StringSequence.idl"

module CF {
  
	
	/* The LifeCycle interface defines the generic operations for initializing or releasing an instantiated 
	component specific data and/or processing elements. */
	
	interface LifeCycle {
		/* This exception indicates an error occurred during component initialization. The messages provides 
		additional information describing the reason why the error occurred. */
		
		exception InitializeError {
			StringSequence errorMessages;
		};
		
		/* This exception indicates an error occurred during component releaseObject. The messages provides 
		additional information describing the reason why the errors occurred. */
		
		exception ReleaseError {
			StringSequence errorMessages;
		};
		
		/* The purpose of the initialize operation is to provide a mechanism to set an object to an known 
		initial state.  (For example, data structures may be set to initial values, memory may be allocated, 
		hardware devices may be configured to some state, etc.).

		Initialization behavior is implementation dependent.

		This operation raises the InitializeError when an initialization error occurs.
		@roseuid 37DD15FA01C2 */
		void initialize ()			
			raises (InitializeError);
			
		/* The purpose of the releaseObject operation is to provide a means by which an instantiated component 
		may be torn down. The releaseObject operation releases itself from the CORBA OCPI_CORBA_ORB.  

		The releaseObject operation releases all internal memory allocated by the component during the 
		life of the component. The releaseObject operation tears down the component (i.e. released from 
		the CORBA environment).  The releaseObject operation releases components from the Operating Environment.

		This operation raises a ReleaseError when a release error occurs.
		@roseuid 37DD15FA01C3 */
		void releaseObject ()			
			raises (ReleaseError);
  }; 
};

#pragma version CF::LifeCycle 1.0

#endif
