
/*
 *  Copyright (c) Mercury Federal Systems, Inc., Arlington VA., 2009-2010
 *
 *    Mercury Federal Systems, Incorporated
 *    1901 South Bell Street
 *    Suite 402
 *    Arlington, Virginia 22202
 *    United States of America
 *    Telephone 703-413-0781
 *    FAX 703-413-0784
 *
 *  This file is part of OpenCPI (www.opencpi.org).
 *     ____                   __________   ____
 *    / __ \____  ___  ____  / ____/ __ \ /  _/ ____  _________ _
 *   / / / / __ \/ _ \/ __ \/ /   / /_/ / / /  / __ \/ ___/ __ `/
 *  / /_/ / /_/ /  __/ / / / /___/ ____/_/ / _/ /_/ / /  / /_/ /
 *  \____/ .___/\___/_/ /_/\____/_/    /___/(_)____/_/   \__, /
 *      /_/                                             /____/
 *
 *  OpenCPI is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  OpenCPI is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _PROPERTYSET_IDL
#define _PROPERTYSET_IDL

#include "DataType.idl"

module CF {

	/* The PropertySet interface defines configure and query operations to access component properties/attributes. */
	
	interface PropertySet {
		/* This exception indicates the configuration of a component has failed (no configuration 
		at all was done). The message provides additional information describing the reason why the 
		error occurred. The invalid properties returned indicates the properties that were invalid. */
		
		exception InvalidConfiguration {
			string msg;
			Properties invalidProperties;
		};
		
		/* The PartialConfiguration exception indicates the configuration of a Component was partially 
		successful. The invalid properties returned indicates the properties that were invalid. */
		
		exception PartialConfiguration {
			Properties invalidProperties;
		};
		
		/* The purpose of this operation is to allow id/value pair configuration properties to be assigned to 
		components implementing this interface.

		The configure operation shall assign values to the properties as indicated in the configProperties argument. 
		An component's SPD profile indicates the valid configuration values.  Valid properties for the 
		configure operation are at a minimum the configure readwrite and writeonly properties referenced 
		in the component's SPD.

		The configure operation raises an InvalidConfiguration exception when a configuration error 
		occurs that prevents any property configuration on the component.

		This operation raises PartialConfiguration exception when some configuration properties were 
		successful and some configuration properties were not successful.
		@roseuid 38A583FFC998 */
		void configure (
			in Properties configProperties
			)			
			raises (InvalidConfiguration, PartialConfiguration);
			
		/* The purpose of this operation is to allow a component to be queried to retrieve its properties. 
		If the configProperties are zero size then, the query operation returns all component properties.  
		If the configProperties are not zero size, then the query operation returns only those id/value pairs 
		specified in the configProperties. An component's SPD profile indicates the valid query types. Valid 
		properties for the query operation are at a minimum the configure readwrite and readonly properties, 
		and allocation properties that have an action value of "external" as referenced in the component's SPD.

		This operation raises the CF UnknownProperties exception when one or more properties 
		being requested are not known by the component.
		@roseuid 38A583FFC99A */
		void query (
			inout Properties configProperties
			)			
			raises (UnknownProperties);

  }; 
};

#pragma version CF::PropertySet 1.0

#endif
