
/*
 *  Copyright (c) Mercury Federal Systems, Inc., Arlington VA., 2009-2010
 *
 *    Mercury Federal Systems, Incorporated
 *    1901 South Bell Street
 *    Suite 402
 *    Arlington, Virginia 22202
 *    United States of America
 *    Telephone 703-413-0781
 *    FAX 703-413-0784
 *
 *  This file is part of OpenCPI (www.opencpi.org).
 *     ____                   __________   ____
 *    / __ \____  ___  ____  / ____/ __ \ /  _/ ____  _________ _
 *   / / / / __ \/ _ \/ __ \/ /   / /_/ / / /  / __ \/ ___/ __ `/
 *  / /_/ / /_/ /  __/ / / / /___/ ____/_/ / _/ /_/ / /  / /_/ /
 *  \____/ .___/\___/_/ /_/\____/_/    /___/(_)____/_/   \__, /
 *      /_/                                             /____/
 *
 *  OpenCPI is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  OpenCPI is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with OpenCPI.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _TESTABLEOBJECT_IDL
#define _TESTABLEOBJECT_IDL

#include "DataType.idl"

module CF {
  
	/* The TestableObject interface defines a set of operations that can be used to
	test component implementations. */
	
	interface TestableObject {
		/* This exception indicates the requested testid for a test to be performed is not known by the component. */
		
		exception UnknownTest {
		};
		
		/* The runTest operation allows components to be "blackbox" tested.  This allows Built-In Test (BIT) to be 
		implemented and this provides a means to isolate faults (both software and hardware) within the system.

		The runTest operation uses the testid parameter to determine which of its predefined test implementations 
		should be performed. The testValues parameter Properties (id/value pair(s)) are used to provide additional 
		information to the implementation-specific test to be run.  The runTest operation returns the result(s) 
		of the test in the testValues parameter.

		Tests to be implemented by a component are component-dependent and are specified in the component's 
		Properties Descriptor.  Valid testid(s) and both input and ouput testValues (properties) for the 
		runTest operation, at a minimum, are test properties defined in the properties test element of the 
		component's Properties Descriptor (refer to Appendix D Domain Profile).  The testid parameter 
		corresponds to the XML attribute testid of the property element test in a propertyfile.

		Before an UnknownProperties exception is raised by the runTest operation all inputValues properties are 
		validated (i.e., test properties defined in the propertyfile(s) referenced in the component's SPD).
	
		The runTest operation does not execute any testing when the input testid or any of the the input 
		testValues are not known by the component or are out of range.

		This operation does not return a value.

		The runTest operation raises the UnknownTest exception when there is no underlying test 
		implementation that is associated with the input testid given.

		The runTest operation raises CF UnknownProperties exception when the input parameter testValues 
		contains any DataTypes that are not known by the component's test implementation or any values 
		that are out of range for the requested test. The exception parameter invalidProperties contains 
		the invalid inputValues properties id(s) that are not known by the component or the value(s) are out of range.
		@roseuid 38A583C40208 */
		void runTest (
			in unsigned long testid,
			inout Properties testValues
			)			
			raises (UnknownTest, UnknownProperties);
  }; 
};

#pragma version CF::TestableObject 1.0

#endif
