%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "ocdp"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs  & Fmax (MHz) & Memory/Special Functions                        \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 3238      & 5809  & 224.434    & \begin{tabular}{@{}c@{}}RAMB36E1s=8\end{tabular}\\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 3238      & 5870  & 186.424    & \begin{tabular}{@{}c@{}}RAMB36E1s=8\end{tabular}\\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 3241      & 5465  & 165.508    & \begin{tabular}{@{}c@{}}RAMB36E1s=8\end{tabular}\\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 3686      & 5,247 & N/A        & N/A                                             \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
