% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {6}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: rp\_cordic}\\
        \hline
        \rowcolor{blue}
            Configuration & DATA\_EXT & DATA\_WIDTH & STAGES & ocpi\_endian & ocpi\_debug \\
            \hline
            0             & 6         & 16          & 16     & little       & false \\
            \hline
        \end{longtable}
\end{tiny}
