% Generated on Fri Oct  5 08:45:53 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: rp\_cordic}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1523            & 3481       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 3\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1470            & 2979       & 145.455          & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1529            & 2514       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 12\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
