#!/bin/sh --noprofile
# Load the user-bit-stream flash on a platform
# This script loads the flash, and may also load the same bitstream onto the FPGA in the process,
# or (worse) may trash the currently loaded bitstream.
if test $# != 3; then
  echo "This script loads a bitstream file into the user-loadable boot flash memory on a HDL/FPGA platform/card."
  echo "There must be three arguments, which are:"
  echo "1. The name of the platform, e.g. ml605, alst4, alst4x, etc."
  echo "2. The bitstream file to write into the flash of the card. Usually ending in .bitz"
  echo "3. The serial number of the JTAG pod/cable connected to the card."
  echo "Use the probeJtag command to see whether the platform is reachable."
  exit 1
fi
[ ! -d "$OCPI_CDK_DIR" ] && echo Error: OCPI_CDK_DIR environment variable setting is not valid. && exit 1
source $OCPI_CDK_DIR/scripts/util.sh
if findInProjectPath loadFlash_$1 lib/platforms/$1 pfscript ; then
  echo Loading the flash memory on the $1 platform attached to the JTAG pod with ESN $3
  echo Loading from file: $2
  # do not require execute permission on the file
  exec sh $pfscript $2 $3
fi
echo 'The "'$1'" platform does not appear to be supported for flash loading.  Misspelled?'
echo "Looked for \"loadFlash_$1\" internal script in OCPI_PROJECT_PATH and OCPI_CDK_DIR."
exit 1

