#!/bin/sh

[ ! -d $OCPI_CDK_DIR ] && echo Error: OCPI_CDK_DIR environment setting not valid. && exit 1
echo ==== Probing for Altera JTAG ports:
$OCPI_CDK_DIR/scripts/probeJtag_altera
echo ==== Probing for Xilinx JTAG ports:
$OCPI_CDK_DIR/scripts/probeJtag_xilinx all
