#!/bin/csh -f
# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.


set log=testDMA$$.log
echo Start with $argv >& $log
echo Log is: `pwd`/$log
#set cmd="sudo -E "LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}" testRpl"
set cmd="sudo -E testRpl"

if ($#argv == 0) then
   echo Usage is: testDMA "<DP-roles> <nbufs> <message-sizes> <message-counts> [bd1] [bd2]"
   echo Example: testDMA '"f" "1 2" "0 16" "1 1000"'
   exit 1
endif
if ($#argv >= 5) then
   set args="$argv[5-]"
else
   set args=""
endif
foreach r1i ($1)
  foreach r3o ($1)
    foreach n0o ($2)
      foreach n1i ($2)
        foreach n3o ($2)
          foreach n0i ($2)
            foreach I ($3)
              foreach i ($4)
                if ($#argv == 6) then
		  # two boards
		  foreach r6o ($1)
                    foreach n4i ($2)
		      foreach n6o ($2)
		        set params="-r1i$r1i -r3om -N0o $n0o -N1i $n1i -N3o $n3o -N0i $n0i -I $I -i $i -N4i $n4i -r6o$r6o -N6o $n6o"
			echo -n For $params $args ..." "
		        echo For $params $args >>& $log
		        $cmd $params $args >>& $log
			if ($status != 0) then
			  echo FAILED
			  exit 1
			else
			  echo SUCCEEDED
			endif
		      end
		    end
		  end
		else
		  set params="-r1i$r1i -r3o$r3o -N0o $n0o -N1i $n1i -N3o $n3o -N0i $n0i -I $I -i $i"
		  echo -n For $params $args ..." "
		  echo For $params $args >>& $log
                  $cmd $params $args >>& $log
		  if ($status != 0) then
		    echo FAILED
		    exit 1
		  else
		    echo SUCCEEDED
		  endif
		  if ($status != 0) exit
                endif
end
end
end
end
end
end
end
end
echo "testDMA done"
