#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>


#define D2E7  128.0
#define D2E15 32768.0
#define NPTS  4096
#define PI    3.1415926536
#define FREQ  64.0  // In samples per radian, divide by 2 to get fraction of Nyquist
#define GAIN  0.99

int main(int argc, char *argv[])
{
FILE *verhex0, *fopen(), *cbinf;
char clname[256];
int32_t w[NPTS];
int16_t tmp16;
int i;
double phi, dphi, cosphi;

	if (argc == 2) strcpy(clname, argv[1]);
	else           strcpy(clname, "costable.hex");
	if ((verhex0 = fopen(clname, "w")) == NULL)
    printf("oops, cannot open %s .\n", clname);

  cbinf = fopen("cosbin", "w");

  phi  = 0.0;
  dphi = 2.*PI / FREQ;

  fprintf(verhex0, "// Generated by cosgen...\n");
  fprintf(verhex0, "// Freq:%1.4lf (samples per radian)\n",FREQ);
  fprintf(verhex0, "// Freq:%1.4lf (fraction of Nyquist)\n",1/FREQ*2);
  fprintf(verhex0, "// Gain:%1.4lf\n",GAIN);

  for(i=0; i<NPTS ;i++) {
    cosphi = cos(phi);
    w[i] = (int32_t) (cosphi * D2E15 * GAIN + 0.5);
    printf("i:%4d phi:%1.4lf cosphi:%1.4lf w:%04x \n", i, phi, cosphi, w[i]&0xFFFF);
    fprintf(verhex0, "  16'h%04x, // i:%4d phi:%1.4lf cosphi:%1.4lf \n", w[i]&0xFFFF, i, phi, cosphi);
    tmp16 = (int16_t) w[i];
    fwrite(&tmp16, 2, 1, cbinf);
    phi += dphi;
  }

	fclose(verhex0);
	fclose(cbinf);
	exit(0);
}
