% Generated on Fri Oct  5 08:45:38 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: sma}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 827             & 1144       & N/A              & \begin{tabular}{@{}l@{}}RAMB36E1: 3 \\ RAMB18E1: 1\end{tabular} \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 942             & 1291       & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 125138\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 817             & 1567       & 257.961          & \begin{tabular}{@{}l@{}}RAMB36E1: 3\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
