%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "sma"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs  & Fmax (MHz) & Memory/Special Functions                        \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 817       & 1326  & 296.346    & \begin{tabular}{@{}c@{}}RAMB36E1s=3\end{tabular}\\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 817       & 1567  & 257.961    & \begin{tabular}{@{}c@{}}RAMB36E1s=3\end{tabular}\\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 827       & 1064  & 217.675    & \begin{tabular}{@{}c@{}}RAMB36E1s=3\end{tabular}\\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 942       & 1,291 & N/A        & N/A                                             \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
