% Generated on Fri Sep 28 16:13:50 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {1}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: sdp\_pipeline}\\
        \hline
        \rowcolor{blue}
            Configuration \\
            \hline
            0 \\
            \hline
        \end{longtable}
\end{tiny}
