%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "sdp_pipeline"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 198       & 236  & 471.622    & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 198       & 236  & 373.305    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 3142      & 754  & 595.593    & N/A                     \\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 3142      & 958  & N/A        & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
