% Generated on Fri Oct  5 08:45:35 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: bias}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 352             & 447        & N/A              & N/A \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 468             & 469        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 210\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 352             & 520        & 373.497          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
