%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "bias"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 352       & 515  & 412.619    & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 352       & 520  & 373.497    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 352       & 434  & 350.631    & N/A                     \\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 468       & 469  & N/A        & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
