% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "cic\_int\_dc\_offset\_iq\_imbalance\_mixer\_cic\_dec"}\\
        \hline
        \rowcolor{blue}
            Container                                               & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_fmcomms\_2\_3\_hpc\_LVDS\_ml605 & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 20178           & 27945      & 125.266          & \begin{tabular}{@{}l@{}}BUFGCTRL: 7 \\ BUFG: 7 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 10045           & 13815      & 100.09           & \begin{tabular}{@{}l@{}}BUFGCTRL: 3 \\ BUFG: 3 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 12595           & 12002      & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 3 \\ BUFG: 3 \\ RAMB36E1: 37 \\ DSP48E1: 15 \\ RAMB18E1: 1\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_matchstiq\_z1                   & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 16488           & 14975      & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 3 \\ BUFG: 3 \\ RAMB36E1: 53 \\ DSP48E1: 15 \\ RAMB18E1: 3\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_hpc\_ml605              & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 20178           & 27945      & 125.266          & \begin{tabular}{@{}l@{}}BUFGCTRL: 7 \\ BUFG: 7 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_hsmc\_a\_alst4          & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 61375           & 39461      & N/A              & \begin{tabular}{@{}l@{}}DSP18: 26 \\ GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 845428 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_hsmc\_b\_alst4          & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 61375           & 39461      & N/A              & \begin{tabular}{@{}l@{}}DSP18: 26 \\ GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 845428 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_lpc\_ml605              & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 20178           & 27945      & 125.266          & \begin{tabular}{@{}l@{}}BUFGCTRL: 7 \\ BUFG: 7 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_lpc\_zed                & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 10045           & 13815      & 100.09           & \begin{tabular}{@{}l@{}}BUFGCTRL: 3 \\ BUFG: 3 \\ DSP48E1: 15\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_lpc\_zed                & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 12595           & 12002      & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 3 \\ BUFG: 3 \\ RAMB36E1: 37 \\ DSP48E1: 15 \\ RAMB18E1: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
