% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {7}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: lime\_adc}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_debug & DRIVE\_CLK\_p & USE\_CTL\_CLK\_p & USE\_CLK\_OUT\_p & ocpi\_endian & USE\_CLK\_IN\_p \\
            \hline
            0             & false       & 0             & 0                & 1                & little       & 0 \\
            \hline
            1             & false       & 0             & 0                & 0                & little       & 1 \\
            \hline
        \end{longtable}
\end{tiny}
