% Generated on Fri Oct  5 08:46:00 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker: lime\_adc}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 274             & 153        & N/A              & \begin{tabular}{@{}l@{}}RAMB36E1: 3 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 270             & 258        & 356.069          & \begin{tabular}{@{}l@{}}RAMB36E1: 3 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 273             & 214        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 98304\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 274             & 153        & N/A              & \begin{tabular}{@{}l@{}}RAMB36E1: 3 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 270             & 258        & 356.069          & \begin{tabular}{@{}l@{}}RAMB36E1: 3 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 273             & 214        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 98304\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
