% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "lime\_adc"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 273             & 201        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 98304\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 303             & 217        & N/A              & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 3\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 298             & 283        & 348.335          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 3\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 298             & 299        & 311.439          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 3\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 273             & 201        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 98304\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 303             & 217        & N/A              & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 3\end{tabular} \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 298             & 283        & 348.335          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 3\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 298             & 299        & 311.439          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 3\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
