%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "lime_adc"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+DRIVE_CLK_p=0+
	\item \verb+ocpi_endian=little+
	\item \verb+USE_CLK_OUT_p=1+
	\item \verb+USE_CTL_CLK_p=0+
	\item \verb+USE_CLK_IN_p=0+
	\item \verb+ocpi_debug=false+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions                                                  \\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 273       & 214  & N/A        & N/A                                                                       \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 270       & 258  & 356.069    & \begin{tabular}{@{}c@{}}BUFG/BUFGCTRLs=1\end{tabular}                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 274       & 153  & 308.452    & \begin{tabular}{@{}c@{}}BUFGs=1 \\ RAMB36E1s=3 \\ BUFGCTRLs=1\end{tabular}\\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 270       & 231  & 468.033    & \begin{tabular}{@{}c@{}}BUFG/BUFGCTRLs=1\end{tabular}                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
\textbf{Worker Build Configuration ``1'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+DRIVE_CLK_p=0+
	\item \verb+ocpi_endian=little+
	\item \verb+USE_CLK_OUT_p=0+
	\item \verb+USE_CTL_CLK_p=0+
	\item \verb+USE_CLK_IN_p=1+
	\item \verb+ocpi_debug=false+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``1''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions                                                  \\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 273       & 214  & N/A        & N/A                                                                       \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 270       & 258  & 356.069    & \begin{tabular}{@{}c@{}}BUFG/BUFGCTRLs=1\end{tabular}                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 274       & 153  & 308.452    & \begin{tabular}{@{}c@{}}BUFGs=1 \\ RAMB36E1s=3 \\ BUFGCTRLs=1\end{tabular}\\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 270       & 231  & 468.033    & \begin{tabular}{@{}c@{}}BUFG/BUFGCTRLs=1\end{tabular}                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
