% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {3}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: complex\_mixer\_ts}\\
        \hline
        \rowcolor{blue}
            Configuration & INPUT\_DATA\_WIDTH\_p & NCO\_DATA\_WIDTH\_p \\
            \hline
            0             & 12                    & 12 \\
            \hline
            1             & 16                    & 16 \\
            \hline
        \end{longtable}
\end{tiny}
