% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "complex\_mixer\_ts"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 1432            & 1823       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 8\end{tabular} \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 1382            & 2928       & 293.703          & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 1383            & 2971       & 263.336          & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 1360            & 2676       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 1636            & 2029       & N/A              & \begin{tabular}{@{}l@{}}DSP18: 12\end{tabular} \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 1578            & 3442       & 220.985          & \begin{tabular}{@{}l@{}}DSP48E1: 8\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 1578            & 3442       & 195.385          & \begin{tabular}{@{}l@{}}DSP48E1: 8\end{tabular} \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 1590            & 3221       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
