% Generated on Mon Feb 25 10:09:54 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "complex\_mixer"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool   & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado & 2017.1  & xc7z020clg400-3 & 1277            & 2600       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
            1             & zynq        & Vivado & 2017.1  & xc7z020clg400-3 & 1509            & 3142       & N/A              & \begin{tabular}{@{}l@{}}DSP48E1: 6\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
