Core=pcie_4243_trn_v5_gtx_x8_125
Top=endpoint_blk_plus_v1_14
ExcludeTargets=
OnlyTargets=virtex5
SourceFiles=\
# end of files
PreBuiltCore=endpoint_blk_plus_v1_14.ngc
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk
