Core=ddc_4243_4ch_v5
Top=duc_ddc_compiler_v1_0
ExcludeTargets=
OnlyTargets=virtex5 isim
SourceFiles=\
 duc_ddc_compiler_v1_0.v\
# end of files
PreBuiltCore=duc_ddc_compiler_v1_0.ngc
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk
