Core=fft_v5_4k_strm_nat
Top=xfft_v7_1
ExcludeTargets=
OnlyTargets=virtex5 isim xsim
SourceFiles=\
 xfft_v7_1.v\
# end of files
PreBuiltCore=xfft_v7_1.ngc
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk
