% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: cic\_dec}\\
        \hline
        \rowcolor{blue}
            Configuration & DOUT\_WIDTH & ocpi\_debug & M & R    & DIN\_WIDTH & ocpi\_endian & N & ACC\_WIDTH \\
            \hline
            0             & 16          & false       & 1 & 4    & 16         & little       & 3 & 22 \\
            \hline
            1             & 16          & false       & 2 & 4    & 16         & little       & 3 & 25 \\
            \hline
            2             & 16          & false       & 1 & 5    & 16         & little       & 3 & 23 \\
            \hline
            3             & 16          & false       & 2 & 5    & 16         & little       & 3 & 26 \\
            \hline
            4             & 16          & false       & 1 & 8    & 16         & little       & 3 & 25 \\
            \hline
            5             & 16          & false       & 1 & 16   & 16         & little       & 3 & 28 \\
            \hline
            6             & 16          & false       & 1 & 2048 & 16         & little       & 3 & 49 \\
            \hline
            7             & 16          & false       & 2 & 2048 & 16         & little       & 3 & 52 \\
            \hline
            8             & 16          & false       & 1 & 2048 & 16         & little       & 4 & 60 \\
            \hline
            9             & 16          & false       & 1 & 8191 & 16         & little       & 3 & 55 \\
            \hline
            10            & 16          & false       & 2 & 8191 & 16         & little       & 3 & 58 \\
            \hline
            11            & 16          & false       & 1 & 8192 & 16         & little       & 3 & 55 \\
            \hline
            12            & 16          & false       & 2 & 8192 & 16         & little       & 3 & 58 \\
            \hline
        \end{longtable}
\end{tiny}
