% Generated on Fri Sep 28 16:14:05 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: cic\_dec}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_endian & ACC\_WIDTH & DOUT\_WIDTH & M & N & DIN\_WIDTH & ocpi\_debug & R \\
            \hline
            0             & little       & 22         & 16          & 1 & 3 & 16         & false       & 4 \\
            \hline
            1             & little       & 25         & 16          & 2 & 3 & 16         & false       & 4 \\
            \hline
            2             & little       & 23         & 16          & 1 & 3 & 16         & false       & 5 \\
            \hline
            3             & little       & 26         & 16          & 2 & 3 & 16         & false       & 5 \\
            \hline
            4             & little       & 25         & 16          & 1 & 3 & 16         & false       & 8 \\
            \hline
            5             & little       & 28         & 16          & 1 & 3 & 16         & false       & 16 \\
            \hline
            6             & little       & 49         & 16          & 1 & 3 & 16         & false       & 2048 \\
            \hline
            7             & little       & 52         & 16          & 2 & 3 & 16         & false       & 2048 \\
            \hline
            8             & little       & 60         & 16          & 1 & 4 & 16         & false       & 2048 \\
            \hline
            9             & little       & 55         & 16          & 1 & 3 & 16         & false       & 8191 \\
            \hline
            10            & little       & 58         & 16          & 2 & 3 & 16         & false       & 8191 \\
            \hline
            11            & little       & 55         & 16          & 1 & 3 & 16         & false       & 8192 \\
            \hline
            12            & little       & 58         & 16          & 2 & 3 & 16         & false       & 8192 \\
            \hline
        \end{longtable}
\end{tiny}
