% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "cic\_dec"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 727             & 450        & N/A              & N/A \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 725             & 520        & N/A              & N/A \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 722             & 668        & 289.185          & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 722             & 668        & 267.881          & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 931             & 486        & N/A              & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 929             & 556        & N/A              & N/A \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 926             & 704        & 289.185          & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 926             & 704        & 267.881          & N/A \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 746             & 464        & N/A              & N/A \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 745             & 534        & N/A              & N/A \\
            \hline
            2             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 742             & 682        & 289.185          & N/A \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 742             & 682        & 267.881          & N/A \\
            \hline
            3             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 956             & 500        & N/A              & N/A \\
            \hline
            3             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 955             & 570        & N/A              & N/A \\
            \hline
            3             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 952             & 718        & 289.185          & N/A \\
            \hline
            3             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 952             & 718        & 267.881          & N/A \\
            \hline
            4             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 782             & 488        & N/A              & N/A \\
            \hline
            4             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 781             & 558        & N/A              & N/A \\
            \hline
            4             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 778             & 706        & 289.185          & N/A \\
            \hline
            4             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 778             & 706        & 267.881          & N/A \\
            \hline
            5             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 837             & 524        & N/A              & N/A \\
            \hline
            5             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 837             & 594        & N/A              & N/A \\
            \hline
            5             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 834             & 743        & 289.185          & N/A \\
            \hline
            5             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 834             & 743        & 267.881          & N/A \\
            \hline
            6             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1222            & 798        & N/A              & N/A \\
            \hline
            6             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1229            & 858        & N/A              & N/A \\
            \hline
            6             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1226            & 1018       & 289.185          & N/A \\
            \hline
            6             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1226            & 1016       & 267.881          & N/A \\
            \hline
            7             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1588            & 834        & N/A              & N/A \\
            \hline
            7             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1595            & 894        & N/A              & N/A \\
            \hline
            7             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1592            & 1054       & 289.185          & N/A \\
            \hline
            7             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1592            & 1052       & 267.881          & N/A \\
            \hline
            8             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1780            & 1170       & N/A              & N/A \\
            \hline
            8             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1787            & 1230       & N/A              & N/A \\
            \hline
            8             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1784            & 1390       & 289.185          & N/A \\
            \hline
            8             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1784            & 1388       & 267.881          & N/A \\
            \hline
            9             & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1332            & 872        & N/A              & N/A \\
            \hline
            9             & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1341            & 957        & N/A              & N/A \\
            \hline
            9             & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1338            & 1120       & 289.185          & N/A \\
            \hline
            9             & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1338            & 1124       & 267.881          & N/A \\
            \hline
            10            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1734            & 908        & N/A              & N/A \\
            \hline
            10            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1743            & 993        & N/A              & N/A \\
            \hline
            10            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1740            & 1156       & 289.185          & N/A \\
            \hline
            10            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1740            & 1160       & 267.881          & N/A \\
            \hline
            11            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1332            & 872        & N/A              & N/A \\
            \hline
            11            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1341            & 956        & N/A              & N/A \\
            \hline
            11            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1338            & 1120       & 289.185          & N/A \\
            \hline
            11            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1338            & 1124       & 267.881          & N/A \\
            \hline
            12            & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 1734            & 908        & N/A              & N/A \\
            \hline
            12            & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 1743            & 992        & N/A              & N/A \\
            \hline
            12            & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 1740            & 1156       & 289.185          & N/A \\
            \hline
            12            & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 1740            & 1160       & 267.881          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
