%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "cic_dec"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+DOUT_WIDTH=16+
	\item \verb+DIN_WIDTH=16+
	\item \verb+ACC_WIDTH=22+
	\item \verb+M=1+
	\item \verb+N=3+
	\item \verb+ocpi_endian=little+
	\item \verb+R=4+
	\item \verb+ocpi_debug=false+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 629       & 454  & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 628       & 550  & 346.081    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 630       & 415  & 228.938    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 628       & 547  & 362.845    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
%\textbf{Worker Build Configuration ``1'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=25+
%	\item \verb+M=2+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=4+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``1''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 833       & 490  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 832       & 586  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 834       & 451  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 832       & 583  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``2'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=23+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=5+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``2''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 648       & 467  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 648       & 564  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 650       & 429  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 648       & 561  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``3'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=26+
%	\item \verb+M=2+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=5+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``3''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 858       & 504  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 858       & 600  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 860       & 465  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 858       & 597  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``4'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=25+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=8+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``4''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 684       & 491  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 684       & 588  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 686       & 453  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 684       & 585  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``5'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=28+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=16+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``5''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 739       & 529  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 740       & 625  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 742       & 489  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 740       & 622  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``6'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=49+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=2048+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``6''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1124      & 777  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 1132      & 894  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1134      & 755  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 1132      & 796  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``7'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=52+
%	\item \verb+M=2+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=2048+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``7''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1490      & 820  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 1498      & 830  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1500      & 791  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 1498      & 832  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``8'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=60+
%	\item \verb+M=1+
%	\item \verb+N=4+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=2048+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``8''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs  & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1682      & 1,156 & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 1690      & 1166  & 343.938    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1692      & 1128  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 1690      & 1168  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``9'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=55+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=8191+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``9''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1234      & 859  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 1244      & 896  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1246      & 863  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 1244      & 896  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``10'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=58+
%	\item \verb+M=2+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=8191+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``10''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1636      & 895  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 1646      & 932  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1648      & 899  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 1646      & 932  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``11'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=55+
%	\item \verb+M=1+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=8192+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``11''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1234      & 859  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 1244      & 896  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1246      & 863  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 1244      & 896  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``12'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+DOUT_WIDTH=16+
%	\item \verb+DIN_WIDTH=16+
%	\item \verb+ACC_WIDTH=58+
%	\item \verb+M=2+
%	\item \verb+N=3+
%	\item \verb+ocpi_endian=little+
%	\item \verb+R=8192+
%	\item \verb+ocpi_debug=false+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``12''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 1636      & 895  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 1646      & 932  & 346.081    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 1648      & 899  & 228.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 1646      & 932  & 362.845    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
