
# Put Makefile customizations for worker jm.rcc here:
SourceFiles = matrix.cilk
Path = /work/kulp/cilk/cilk/lib64
#Libraries =   cilkrts cilkutil
LinkFiles = matrix.o

include $(OCPI_CDK_DIR)/include/worker.mk








