# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

# This core was generated for one target
Top=s6_pcie_v1_2
OnlyTargets=xc6slx45t
Imports= $(OCPI_HDL_IMPORTS_DIR)/coregen/pcie_4243_trn_s6_x1_125/source/*.v
include $(OCPI_CDK_DIR)/include/hdl/hdl-core.mk # We are a (compiled) core






