%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "bias_ver"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 129       & 42   & 702.000    & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 129       & 45   & 587.458    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 129       & 42   & 494.560    & N/A                     \\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 128       & 50   & N/A        & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
