%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "sdp_receive"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs  & Fmax (MHz) & Memory/Special Functions                         \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 954       & 1604  & 356.721    & \begin{tabular}{@{}c@{}}RAMB36E1s=16\end{tabular}\\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 954       & 1592  & 289.683    & \begin{tabular}{@{}c@{}}RAMB36E1s=16\end{tabular}\\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 956       & 1037  & 225.836    & \begin{tabular}{@{}c@{}}RAMB36E1s=16\end{tabular}\\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 1057      & 1,083 & N/A        & N/A                                              \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
