% Generated on Tue Apr 30 11:23:58 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "sdp\_receive"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 983             & 1756       & 353.582          & \begin{tabular}{@{}l@{}}RAMB36E1: 16\end{tabular} \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 986             & 1132       & N/A              & \begin{tabular}{@{}l@{}}RAMB36E1: 16\end{tabular} \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 1088            & 1188       & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 524387\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 983             & 1787       & 289.826          & \begin{tabular}{@{}l@{}}RAMB36E1: 16\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
