# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

#Top=pcie_hip_s4gx_gen2_x4_128
ExcludeTargets=
OnlyTargets=stratix4
SourceFiles=\
 pcie_hip_s4gx_gen2_x4_128.v\
 pcie_hip_s4gx_gen2_x4_128_core.v\
 pcie_hip_s4gx_gen2_x4_128_serdes.v\
 altpcie_hip_pipen1b.v\
 pciexp_dcram.v\
 altpcie_rs_serdes.v\
# end of files
include $(OCPI_CDK_DIR)/include/hdl/hdl-lib.mk
