% Generated on Fri Oct  5 08:47:39 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: fsk\_modem}\\
        \hline
        \rowcolor{blue}
            Container                                               & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_ml605 & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 31989           & 43060      & 125.078          & \begin{tabular}{@{}l@{}}DSP48E1: 153 \\ BUFG: 8 \\ BUFGCTRL: 8\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 26371           & 23131      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 148 \\ RAMB18E1: 1 \\ RAMB36E1: 37 \\ BUFG: 3 \\ BUFGCTRL: 3\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_matchstiq\_z1                   & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 27424           & 24148      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 148 \\ RAMB18E1: 3 \\ RAMB36E1: 37 \\ BUFG: 3 \\ BUFGCTRL: 3\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_hpc\_ml605              & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 31989           & 43060      & 125.078          & \begin{tabular}{@{}l@{}}DSP48E1: 153 \\ BUFG: 8 \\ BUFGCTRL: 8\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_hsmc\_a\_alst4          & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 75377           & 55173      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 845430 \\ PLL: 1 \\ DSP18: 302 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_hsmc\_b\_alst4          & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 75377           & 55173      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 845430 \\ PLL: 1 \\ DSP18: 302 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_lpc\_ml605              & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 31989           & 43060      & 125.078          & \begin{tabular}{@{}l@{}}DSP48E1: 153 \\ BUFG: 8 \\ BUFGCTRL: 8\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_zipper\_lpc\_zed                & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 26371           & 23131      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 148 \\ RAMB18E1: 1 \\ RAMB36E1: 37 \\ BUFG: 3 \\ BUFGCTRL: 3\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
