% Generated on Tue Apr 30 11:23:58 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {2}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: time\_server}\\
        \hline
        \rowcolor{blue}
            Configuration & frequency \\
            \hline
            0             & 100000000.0 \\
            \hline
            1             & 50000000.0 \\
            \hline
            2             & 200000000.0 \\
            \hline
            3             & 125000000.0 \\
            \hline
        \end{longtable}
\end{tiny}
