% Generated on Tue Apr 30 11:23:58 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "time\_server"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 1109            & 1031       & 346.049          & N/A \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 1177            & 734        & N/A              & N/A \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 1087            & 745        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 128\end{tabular} \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 1109            & 1034       & 290.343          & N/A \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 1109            & 1212       & 347.064          & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 1177            & 731        & N/A              & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 1087            & 745        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 128\end{tabular} \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 1109            & 1035       & 291.799          & N/A \\
            \hline
            2             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 1109            & 1025       & 344.541          & N/A \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 1177            & 729        & N/A              & N/A \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & N/A             & 1087            & 742        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 128\end{tabular} \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 1109            & 1182       & 288.476          & N/A \\
            \hline
            3             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 1109            & 1034       & 346.049          & N/A \\
            \hline
            3             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 1177            & 731        & N/A              & N/A \\
            \hline
            3             & stratix4    & Quartus & 17.1.0  & N/A             & 1087            & 743        & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 128\end{tabular} \\
            \hline
            3             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 1109            & 1037       & 290.343          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
