% Generated on Tue Apr 30 11:23:58 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "bias\_vhdl"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 390             & 625        & 334.169          & N/A \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 382             & 390        & N/A              & N/A \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 385             & 1014       & N/A              & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 392             & 559        & 248.961          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
