% Generated on Fri Oct  5 08:46:36 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: data\_src\_to\_dac\_test\_tx\_event}\\
        \hline
        \rowcolor{blue}
            Container                                                          & OCPI Platform & OCPI Target & Tool   & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_eventasmout\_fmcomms\_2\_3\_lpc\_LVDS\_ml605 & ml605         & virtex6     & ISE    & 14.7    & 6vlx240tff1156-1 & 5780            & 6267       & 126.072          & \begin{tabular}{@{}l@{}}BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_eventasmout\_fmcomms\_2\_3\_lpc\_LVDS\_zed   & zed           & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 2907            & 2932       & 245.761          & \begin{tabular}{@{}l@{}}RAMB18E1: 1 \\ BUFR: 2 \\ RAMB36E1: 2 \\ BUFG: 1 \\ ODDR: 8 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_eventasmout\_matchstiq\_z1                   & matchstiq\_z1 & zynq        & Vivado & 2017.1  & xc7z020clg484-1  & 4393            & 4590       & 100.0            & \begin{tabular}{@{}l@{}}RAMB18E1: 3 \\ RAMB36E1: 2 \\ BUFG: 3 \\ BUFGCTRL: 3\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
