$(if $(OCPI_CDK_DIR),,$(error The OCPI_CDK_DIR environment variable must be set for this Makefile.))

Package=org.opencpi

Implementations = \
	wsi_32_to_16.hdl

export HdlLibraries= bsv

include $(OCPI_CDK_DIR)/include/lib.mk


