% Generated on Tue Apr 30 11:23:25 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: ad9361\_spi\_ts}\\
        \hline
        \rowcolor{blue}
            Configuration & ocpi\_endian & ocpi\_debug & SPI\_CLK\_FREQ\_HZ\_p & CP\_CLK\_FREQ\_HZ\_p \\
            \hline
            0             & little       & false       & 6250000.0             & 100000000.0 \\
            \hline
            1             & little       & false       & 6250000.0             & 125000000.0 \\
            \hline
        \end{longtable}
\end{tiny}
