#!/bin/csh -f
# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

# Update all the known bsv-generated verilog workers.
# run this from the top level of the device worker library
set ib=$OCPI_CDK_DIR/scripts/importBsv
$ib dram_v6 mkDramServer_v6
$ib dram_v5 mkDramServer_v5
$ib flash mkFlashWorker
$ib icap mkICAPWorker
$ib gbe mkGbeWorker
$ib adcx mkADCWorker
$ib dac mkDACWorker
