% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {5}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: fmcomms\_2\_3\_i2c}\\
        \hline
        \rowcolor{blue}
            Configuration & FMC\_GA0 & CP\_CLK\_FREQ\_p & FMC\_GA1 & I2C\_CLK\_FREQ\_p \\
            \hline
            0             & 0        & 100000000.0      & 0        & 250000.0 \\
            \hline
            1             & 1        & 100000000.0      & 0        & 250000.0 \\
            \hline
            2             & 0        & 100000000.0      & 1        & 250000.0 \\
            \hline
            3             & 1        & 100000000.0      & 1        & 250000.0 \\
            \hline
            4             & 0        & 125000000.0      & 0        & 250000.0 \\
            \hline
            5             & 1        & 125000000.0      & 0        & 250000.0 \\
            \hline
            6             & 0        & 125000000.0      & 1        & 250000.0 \\
            \hline
            7             & 1        & 125000000.0      & 1        & 250000.0 \\
            \hline
            8             & 0        & 50000000.0       & 0        & 250000.0 \\
            \hline
            9             & 1        & 50000000.0       & 0        & 250000.0 \\
            \hline
            10            & 0        & 50000000.0       & 1        & 250000.0 \\
            \hline
            11            & 1        & 50000000.0       & 1        & 250000.0 \\
            \hline
        \end{longtable}
\end{tiny}
