% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "fmcomms\_2\_3\_i2c"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool    & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 273        & N/A              & N/A \\
            \hline
            0             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 287        & N/A              & N/A \\
            \hline
            0             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 94              & 354        & 384.378          & N/A \\
            \hline
            0             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 94              & 354        & 302.196          & N/A \\
            \hline
            1             & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 286        & N/A              & N/A \\
            \hline
            1             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 293        & N/A              & N/A \\
            \hline
            1             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 94              & 356        & 384.378          & N/A \\
            \hline
            1             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 94              & 356        & 302.196          & N/A \\
            \hline
            2             & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 286        & N/A              & N/A \\
            \hline
            2             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 293        & N/A              & N/A \\
            \hline
            2             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 94              & 356        & 384.378          & N/A \\
            \hline
            2             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 94              & 356        & 302.196          & N/A \\
            \hline
            3             & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 276        & N/A              & N/A \\
            \hline
            3             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 285        & N/A              & N/A \\
            \hline
            3             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 94              & 354        & 384.378          & N/A \\
            \hline
            3             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 94              & 354        & 302.196          & N/A \\
            \hline
            4             & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 273        & N/A              & N/A \\
            \hline
            4             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 288        & N/A              & N/A \\
            \hline
            4             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 94              & 354        & 384.378          & N/A \\
            \hline
            4             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 94              & 354        & 302.196          & N/A \\
            \hline
            5             & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 286        & N/A              & N/A \\
            \hline
            5             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 295        & N/A              & N/A \\
            \hline
            5             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 94              & 356        & 384.378          & N/A \\
            \hline
            5             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 94              & 356        & 302.196          & N/A \\
            \hline
            6             & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 286        & N/A              & N/A \\
            \hline
            6             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 295        & N/A              & N/A \\
            \hline
            6             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 94              & 356        & 384.378          & N/A \\
            \hline
            6             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 94              & 356        & 302.196          & N/A \\
            \hline
            7             & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 276        & N/A              & N/A \\
            \hline
            7             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 287        & N/A              & N/A \\
            \hline
            7             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 94              & 354        & 384.378          & N/A \\
            \hline
            7             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 94              & 354        & 302.196          & N/A \\
            \hline
            8             & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 273        & N/A              & N/A \\
            \hline
            8             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 287        & N/A              & N/A \\
            \hline
            8             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 93              & 352        & 384.378          & N/A \\
            \hline
            8             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 93              & 352        & 302.196          & N/A \\
            \hline
            9             & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 286        & N/A              & N/A \\
            \hline
            9             & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 293        & N/A              & N/A \\
            \hline
            9             & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 93              & 354        & 384.378          & N/A \\
            \hline
            9             & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 93              & 354        & 302.196          & N/A \\
            \hline
            10            & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 286        & N/A              & N/A \\
            \hline
            10            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 293        & N/A              & N/A \\
            \hline
            10            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 93              & 354        & 384.378          & N/A \\
            \hline
            10            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 93              & 354        & 302.196          & N/A \\
            \hline
            11            & stratix4    & Quartus & 17.1.0  & N/A             & 132             & 276        & N/A              & N/A \\
            \hline
            11            & zynq        & Vivado  & 2017.1  & xc7z020clg400-3 & 102             & 285        & N/A              & N/A \\
            \hline
            11            & zynq\_ise   & ISE     & 14.7    & 7z010clg400-3   & 93              & 352        & 384.378          & N/A \\
            \hline
            11            & virtex6     & ISE     & 14.7    & 6vcx75tff484-2  & 93              & 352        & 302.196          & N/A \\
            \hline
        \end{longtable}
\end{tiny}
