%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "fmcomms_2_3_i2c"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\textbf{Worker Build Configuration ``0'':}\\
Table entries are a result of building the worker with the following parameter sets:\
\begin{itemize}
	\item \verb+I2C_CLK_FREQ_p=250e3+
	\item \verb+FMC_GA0=0+
	\item \verb+FMC_GA1=0+
	\item \verb+CP_CLK_FREQ_p=100e6+
\end{itemize}
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
		\hline
		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 273  & N/A        & N/A                     \\
		\hline
		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 94        & 354  & 302.196    & N/A                     \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 287  & 308.166    & N/A                     \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 94        & 354  & 384.378    & N/A                     \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
%\textbf{Worker Build Configuration ``1'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=1+
%	\item \verb+FMC_GA1=0+
%	\item \verb+CP_CLK_FREQ_p=100e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``1''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 286  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 94        & 356  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 293  & 295.334    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 94        & 356  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``2'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=0+
%	\item \verb+FMC_GA1=1+
%	\item \verb+CP_CLK_FREQ_p=100e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``2''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 286  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 94        & 356  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 293  & 295.334    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 94        & 356  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``3'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=1+
%	\item \verb+FMC_GA1=1+
%	\item \verb+CP_CLK_FREQ_p=100e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``3''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 276  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 94        & 354  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 285  & 294.464    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 94        & 354  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``4'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=0+
%	\item \verb+FMC_GA1=0+
%	\item \verb+CP_CLK_FREQ_p=125e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``4''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 273  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 94        & 354  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 288  & 301.841    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 94        & 354  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``5'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=1+
%	\item \verb+FMC_GA1=0+
%	\item \verb+CP_CLK_FREQ_p=125e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``5''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 286  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 94        & 356  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 295  & 275.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 94        & 356  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``6'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=0+
%	\item \verb+FMC_GA1=1+
%	\item \verb+CP_CLK_FREQ_p=125e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``6''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 286  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 94        & 356  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 295  & 275.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 94        & 356  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``7'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=1+
%	\item \verb+FMC_GA1=1+
%	\item \verb+CP_CLK_FREQ_p=125e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``7''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 276  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 94        & 354  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 287  & 275.938    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 94        & 354  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``8'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=0+
%	\item \verb+FMC_GA1=0+
%	\item \verb+CP_CLK_FREQ_p=50e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``8''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 273  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 93        & 352  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 287  & 308.166    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 93        & 352  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``9'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=1+
%	\item \verb+FMC_GA1=0+
%	\item \verb+CP_CLK_FREQ_p=50e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``9''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 286  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 93        & 354  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 293  & 295.334    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 93        & 354  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``10'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=0+
%	\item \verb+FMC_GA1=1+
%	\item \verb+CP_CLK_FREQ_p=50e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``10''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 286  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 93        & 354  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 293  & 295.334    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 93        & 354  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
%\textbf{Worker Build Configuration ``11'':}\\
%Table entries are a result of building the worker with the following parameter sets:\
%\begin{itemize}
%	\item \verb+I2C_CLK_FREQ_p=250e3+
%	\item \verb+FMC_GA0=1+
%	\item \verb+FMC_GA1=1+
%	\item \verb+CP_CLK_FREQ_p=50e6+
%\end{itemize}
%\begin{scriptsize}
%	\begin{table}[H]
%	\captionsetup{justification=raggedright,singlelinecheck=false}
%	\caption{Worker Build Configuration ``11''}
%	\begin{tabular}{|c|c|c|c|c|c|c|c|}
%		\hline
%		\rowcolor{blue}
%		OpenCPI Target & Tool    & Version & Device          & Registers & LUTs & Fmax (MHz) & Memory/Special Functions\\
%		\hline
%		stratix4       & Quartus & 15.1.0  & N/A             & 132       & 276  & N/A        & N/A                     \\
%		\hline
%		virtex6        & ISE     & 14.7    & 6vcx75tff484-2  & 93        & 352  & 302.196    & N/A                     \\
%		\hline
%		zynq           & Vivado  & 2017.1  & xc7z020clg400-3 & 102       & 285  & 294.464    & N/A                     \\
%		\hline
%		zynq\_ise      & ISE     & 14.7    & 7z010clg400-3   & 93        & 352  & 384.378    & N/A                     \\
%		\hline
%	\end{tabular}
%	\end{table}
%\end{scriptsize}
