% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "patternbias\_v2"}\\
        \hline
        \rowcolor{blue}
            Container & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base      & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 10814           & 13195      & 125.818          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5\end{tabular} \\
            \hline
            base      & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 4459            & 5339       & 100.15           & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1\end{tabular} \\
            \hline
            base      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 5769            & 4593       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 18\end{tabular} \\
            \hline
            base      & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 37751           & 22920      & N/A              & \begin{tabular}{@{}l@{}}GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 400612 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            base      & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 6132            & 4788       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 18\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
