% Generated on Fri Oct  5 08:47:32 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: fsk\_filerw}\\
        \hline
        \rowcolor{blue}
            Container & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base      & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 29677           & 39893      & 117.082          & \begin{tabular}{@{}l@{}}DSP48E1: 144 \\ BUFG: 6 \\ BUFGCTRL: 6\end{tabular} \\
            \hline
            base      & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 72708           & 51447      & N/A              & \begin{tabular}{@{}l@{}}Block Memory Bits: 745590 \\ PLL: 1 \\ DSP18: 284 \\ GXB Transmitter PMA: 4 \\ GXB Receiver PCS: 4 \\ GXB Receiver PMA: 4 \\ GXB Transmitter PCS: 4\end{tabular} \\
            \hline
            base      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 23990           & 20472      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 139 \\ RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 24353           & 20666      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 139 \\ RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
            base      & e3xx          & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 24315           & 20725      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 139 \\ RAMB36E1: 34 \\ BUFG: 1 \\ BUFGCTRL: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
