% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "fsk\_filerw"}\\
        \hline
        \rowcolor{blue}
            Container & OCPI Platform & OCPI Target & Tool    & Version & Device           & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base      & alst4         & stratix4    & Quartus & 17.1.0  & EP4SGX230KF40C2  & 73626           & 52082      & N/A              & \begin{tabular}{@{}l@{}}DSP18: 284 \\ GXB Receiver PCS: 4 \\ GXB Transmitter PCS: 4 \\ GXB Transmitter PMA: 4 \\ PLL: 1 \\ Block Memory Bits: 761972 \\ GXB Receiver PMA: 4\end{tabular} \\
            \hline
            base      & zed           & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 25056           & 21862      & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 34 \\ DSP48E1: 139\end{tabular} \\
            \hline
            base      & ml605         & virtex6     & ISE     & 14.7    & 6vlx240tff1156-1 & 30637           & 41283      & 125.109          & \begin{tabular}{@{}l@{}}BUFGCTRL: 5 \\ BUFG: 5 \\ DSP48E1: 144\end{tabular} \\
            \hline
            base      & zed\_ise      & zynq\_ise   & ISE     & 14.7    & 7z020clg484-1    & 20398           & 27189      & 100.341          & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ DSP48E1: 144\end{tabular} \\
            \hline
            base      & matchstiq\_z1 & zynq        & Vivado  & 2017.1  & xc7z020clg484-1  & 25419           & 22065      & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 34 \\ DSP48E1: 139\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
