%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Utilization Report for Worker "agc_real"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{scriptsize}
	\begin{table}[H]
	\captionsetup{justification=raggedright,singlelinecheck=false}
	\caption{Worker Build Configuration ``0''}
	\begin{tabular}{|c|c|c|c|c|c|c|c|}
		\hline
		\rowcolor{blue}
		OpenCPI Target & Tool    & Version & Device             & Registers & LUTs & Fmax (MHz) & Memory/Special Functions                        \\
		\hline
		stratix4       & Quartus & 15.1.0  & EP4SGX230KF40C2    & 694       & 345  & N/A        & \begin{tabular}{@{}c@{}}DSP18x18s=6\end{tabular}\\
		\hline
		virtex6        & ISE     & 14.7    & 6vlx240tff1156-1   & 389       & 426  & 171.910    & \begin{tabular}{@{}c@{}}DSP48E1s=3\end{tabular} \\
		\hline
		zynq           & Vivado  & 2017.1  & xc7z020clg484-1    & 375       & 411  & 168.919    & \begin{tabular}{@{}c@{}}DSP48E1s=3\end{tabular} \\
		\hline
		zynq\_ise      & ISE     & 14.7    & 7z020clg484-1      & 389       & 426  & 168.180    & \begin{tabular}{@{}c@{}}DSP48E1s=3\end{tabular} \\
		\hline
	\end{tabular}
	\end{table}
\end{scriptsize}
