% Generated on Tue Apr 30 11:24:21 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {6}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Table of Worker Configurations for worker: fir\_complex\_sse}\\
        \hline
        \rowcolor{blue}
            Configuration & NUM\_TAPS\_p & ocpi\_debug & COEFF\_WIDTH\_p & ocpi\_endian & DATA\_WIDTH\_p \\
            \hline
            0             & 64           & false       & 16              & little       & 16 \\
            \hline
        \end{longtable}
\end{tiny}
